# Generated by Django 5.2.5 on 2026-09-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SignInCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64)),
                ("window", models.BigIntegerField()),
                ("count", models.PositiveIntegerField(default=0)),
                ("until", models.BigIntegerField(db_index=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "window"), name="safety_signin_key_window"
                    )
                ],
            },
        ),
    ]
