"""The Assurance Receipt specification, held to the code it describes (Phase 6).

``docs/receipt-spec/v4.1.md`` says a third party can verify a receipt with nothing
but the specification and ``tools/verify_receipt.py``. This file is what makes that
sentence checkable. Every vector below is GENERATED BY THE REAL CODE -- the real
routes, rendered to the bytes an auditor receives -- and then judged twice:

* by the offline verifier, loaded from its file (it imports nothing from here);
* by this repository's own verification: the functions the backend already has for
  each step and nothing else -- ``_nesting_depth`` (the #111 bound),
  ``receipt_schema`` and ``UnknownReceiptVersion``, the published schema's required
  members and constants, ``_digest``, ``deployment_receipt`` and ``envelope_over``.

The two must give the same answer, verdict and reason, on every vector -- with one
exception that is the code's design and not a gap in this test. THE BACKEND HOLDS NO
KEYRING AND NEVER CHECKS A SIGNATURE (``envelope_over``: "NOT the signature";
``signed_assurance_receipt``: "Verification is the auditor's job"), AND IT HAS NO
FRESHNESS POLICY -- how old is too old is the reader's (``--max-age``). On a vector
whose only defect is the signature or the age, every check the backend makes passes,
so its answer is no refusal, and the verifier is held instead to the ground truth the
vector was built with: which key signed which bytes, and when the backend's clock said
they were issued.

The signer is a stand-in. athena-engine signs receipts (``POST
/api/assurance/receipt/sign``, ``engine/evidence/envelope.py`` ``wrap``) and this
backend does not import the engine, so ``_Engine`` below signs the way the engine
does -- the engine's canonical bytes, DSSE's pre-authentication encoding bound to the
receipt type, Ed25519 -- with keys generated here. No key is read from anywhere, and
none is printed.
"""

from __future__ import annotations

import ast
import base64
import hashlib
import importlib.util
import json
import re
import subprocess
import sys
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from pathlib import Path

import pytest
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat
from django.contrib.auth import get_user_model
from rest_framework.test import APIRequestFactory, force_authenticate

from ai_engine.services.cyberengine_client import (
    ENGINE_UNREACHABLE,
    MAX_JSON_DEPTH,
    CyberEngineClient,
    EngineError,
    _nesting_depth,
)
from assurance import composition, receipt
from assurance.models import (
    Asset,
    Deployment,
    Evidence,
    EvidenceClass,
    Finding,
    Provider,
    ProviderAssertion,
)
from assurance.views import DeploymentViewSet, FindingViewSet
from tests.decision_surfaces import stamped_under_the_rules_in_force
from tests.receipt_schema_reading import shapes_read

ROOT = Path(__file__).resolve().parent.parent
VERIFIER_PATH = ROOT / "tools" / "verify_receipt.py"
SPEC_DIR = ROOT / "docs" / "receipt-spec"
#: The specification file is named for the version the code emits, so a version bump
#: with no specification for it fails here.
SPEC_PATH = SPEC_DIR / f"v{receipt.RECEIPT_VERSION.rsplit('/', 1)[1]}.md"

User = get_user_model()


def _load_verifier():
    """The verifier as an auditor has it: a file, loaded by path, not a module of this
    repository. Registered in ``sys.modules`` under its own name only because
    dataclasses look their module up there."""
    spec = importlib.util.spec_from_file_location("verify_receipt_under_test", VERIFIER_PATH)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


verifier = _load_verifier()

#: Every vector: its name, what it was built to be ("verified" or a refusal), and
#: whether its only defect is one only the verifier checks -- the signature, or the
#: age a reader allows (--max-age) -- the two checks the backend never makes.
VECTORS = (
    ("signed receipt", "verified", False),
    ("signed receipt, its key since retired", "verified", False),
    ("signed receipt, with the evidence it covers", "verified", False),
    ("unsigned copy", "unsigned", False),
    ("unsigned copy, members reordered and whitespace changed", "unsigned", False),
    ("signed route, the engine unreachable", "unsigned", False),
    ("signed route, the signer's payload past the depth limit (#111)", "unsigned", False),
    ("unsigned copy, the decision altered", "digest_mismatch", False),
    ("unsigned copy, a version nobody defined", "unknown_version", False),
    ("unsigned copy, a required member removed", "malformed", False),
    ("the served copy altered beside a genuine envelope", "different_document", False),
    ("an evidence-pack signature presented as a receipt", "not_an_envelope", False),
    ("an envelope whose payload nests past the limit", "depth_limit", False),
    ("checked against the wrong key", "wrong_key", True),
    ("signed by a key the keyring revoked", "revoked_key", True),
    ("the signed payload re-serialised after signing", "bad_signature", True),
    # 4.1 on: the time a receipt was issued, under the signature.
    ("signed receipt, within --max-age, its issue time shown", "verified", False),
    ("signed receipt, its issue time edited after signing", "bad_signature", True),
    ("signed receipt, issued longer ago than --max-age", "stale", True),
    # 5.0: the authority chains, read by the verifier as well as digested.
    ("signed 4.1 receipt, which carries no authority chains", "verified", False),
    ("unsigned copy, a chain reading proven over an unproven hop", "malformed", False),
    # 6.0: the consequential effects, read against the chains the receipt holds.
    ("signed 5.0 receipt, which carries no consequential effects", "verified", False),
    ("unsigned copy, a consequential effect covered by no chain", "malformed", False),
    ("signed 4.0 receipt, which carries no issue time", "verified", False),
    ("signed 4.0 receipt under --max-age", "no_signed_time", True),
    # Every version ever emitted reads back: generated from git, at the commits that
    # emitted them (tests/fixtures/receipts), never typed in.
    ("1.0 unsigned copy, as #27 emitted it", "unsigned", False),
    ("2.0 unsigned copy, as #56 emitted it", "unsigned", False),
    ("2.0 unsigned copy, as #67 emitted it", "unsigned", False),
    ("a signed claim of a 2.0 receipt, a version no route ever signed", "never_signed", False),
    ("an evidence hash altered after the receipt was issued", "evidence_mismatch", False),
)

#: The old-version vectors: what each commit's own route emitted (generate.py).
RECEIPT_FIXTURES = Path(__file__).resolve().parent / "fixtures" / "receipts"

#: The backend's clock, held while the vectors are signed.
ISSUED = datetime(2026, 1, 2, 3, 4, 5, tzinfo=UTC)
ISSUED_TEXT = "2026-01-02T03:04:05Z"
#: The verifier's clock, held while they are checked: a minute after they were issued.
CHECKED = ISSUED + timedelta(seconds=60)
FOUR_OH = "mythos.assurance.receipt/4.0"
FOUR_ONE = "mythos.assurance.receipt/4.1"
FIVE_OH = "mythos.assurance.receipt/5.0"


# ----------------------------------------------------------------- building blocks


def _b64(data: bytes) -> str:
    return base64.b64encode(data).decode("ascii")


def _raw_public(key: Ed25519PrivateKey) -> bytes:
    return key.public_key().public_bytes(Encoding.Raw, PublicFormat.Raw)


def _key_id(key: Ed25519PrivateKey) -> str:
    return "sha256:" + hashlib.sha256(_raw_public(key)).hexdigest()[:32]


def _sign(body: bytes, key: Ed25519PrivateKey, payload_type: str = receipt.ASSURANCE_RECEIPT_TYPE) -> dict:
    """A DSSE envelope over exactly ``body``, as the engine's ``wrap`` builds one."""
    kind = payload_type.encode("utf-8")
    pae = b" ".join([b"DSSEv1", str(len(kind)).encode(), kind, str(len(body)).encode(), body])
    return {
        "envelope_version": 1,
        "payloadType": payload_type,
        "payload": _b64(body),
        "signatures": [{"keyid": _key_id(key), "sig": _b64(key.sign(pae))}],
    }


def _engine_bytes(document: dict) -> bytes:
    """The engine's canonical bytes (``engine.evidence.envelope.canonical_bytes``):
    sorted keys, no whitespace, raw UTF-8 -- NOT the digest's ASCII-escaped form."""
    return json.dumps(document, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")


class _Engine:
    """Stands in for the engine's signing route; see the module docstring."""

    def __init__(self, key: Ed25519PrivateKey | None = None, *, payload=None, fails: Exception | None = None):
        self.key, self.payload, self.fails, self.sent = key, payload, fails, None

    def sign_assurance_receipt(self, document):
        if self.fails is not None:
            raise self.fails
        self.sent = document
        return _sign(self.payload if self.payload is not None else _engine_bytes(document), self.key)


def _keyring(*entries: tuple[Ed25519PrivateKey, str]) -> bytes:
    """A keyring as the engine publishes it at ``GET /api/assurance/keyring``,
    ``caveat`` included."""
    keys = {
        _key_id(key): {
            "public_key": _b64(_raw_public(key)),
            "status": status,
            "created_at": None,
            "retired_at": None,
            "reason": None,
        }
        for key, status in entries
    }
    caveat = (
        "a retired key still verifies receipts it signed; a revoked key verifies nothing, "
        "and every receipt signed with it is invalid"
    )
    return json.dumps({"version": 1, "keys": keys, "caveat": caveat}).encode()


def _user(name: str) -> User:
    return User.objects.create_user(username=name, password="x", role=User.Roles.ADMIN)


def _deployment(owner) -> Deployment:
    """Two findings, three evidence rows, an asset and a provider; a name outside
    ASCII, because the digest escapes it and the signed payload does not."""
    dep = Deployment.objects.create(
        name="Kundenservice-Assistent (Zürich)",
        owner=owner,
        environment=Deployment.Environment.PRODUCTION,
        decision=Deployment.Decision.NEEDS_MORE_EVIDENCE,
    )
    first = Finding.objects.create(
        deployment=dep, fingerprint="fp-first", finding_type="xss", title="F", severity="high"
    )
    Evidence.objects.create(
        finding=first, classification=EvidenceClass.VENDOR_ASSERTED, source="vendor_doc", content_hash="a" * 64
    )
    Evidence.objects.create(
        finding=first, classification=EvidenceClass.PARTIALLY_VERIFIED, source="engine_scan", content_hash="1" * 64
    )
    second = Finding.objects.create(
        deployment=dep, fingerprint="fp-second", finding_type="xss", title="G", severity="medium"
    )
    Evidence.objects.create(
        finding=second,
        classification=EvidenceClass.CONFIGURATION_VERIFIED,
        source="config",
        content_hash="2" * 64,
    )
    provider = Provider.objects.create(name="Acme Model Co", kind=Provider.Kind.MODEL_PROVIDER)
    ProviderAssertion.objects.create(provider=provider, field=ProviderAssertion.Field.REGION, value="us-east-1")
    Asset.objects.create(
        deployment=dep,
        kind=Asset.Kind.MODEL,
        name="gpt-x",
        provider=provider,
        classification=Asset.Classification.APPROVED,
    )
    # One authority chain, so the receipt carries a chain and its hops' verdicts:
    # a person's sign-in this platform holds no record of, so it is unproven.
    from assurance import authority_chain as rule
    from assurance.authority_chain_records import chain_digest, chain_document
    from assurance.models import AuthorityChain

    hops, errors = rule.parse_hops(
        [
            {"from": {"kind": "person", "ref": "employee"}, "relation": "authenticated_as",
             "to": {"kind": "user", "ref": "support-user"}},
            {"from": {"kind": "user", "ref": "support-user"}, "relation": "delegates_to",
             "to": {"kind": "agent", "ref": "support-agent"}},
            {"from": {"kind": "agent", "ref": "support-agent"}, "relation": "performs",
             "to": {"kind": "action", "ref": "customer:update"}},
            {"from": {"kind": "action", "ref": "customer:update"}, "relation": "produces",
             "to": {"kind": "effect", "ref": "customer-record-change"}},
        ],
        "support-update",
    )
    assert not errors, errors
    AuthorityChain.objects.create(
        deployment=dep, workflow="support-update", effect="customer-record-change",
        hops=[h.as_dict() for h in hops],
        digest=chain_digest(chain_document(str(dep.uuid), "support-update", hops, "", "")),
    )
    # The workflow's approval binds two tools, so the receipt carries their effects: a
    # write no chain names (the chain above never invokes it) is missing one, and a
    # read needs none.
    from assurance.models import ApprovedWorkflow
    from assurance.tool_contract import bind_workflow

    workflow = ApprovedWorkflow.objects.create(deployment=dep, slug="support-update", name="Support update")
    for name, effect_class in (("crm-mcp", "write"), ("lookup-mcp", "read")):
        bind_workflow(
            workflow,
            Asset.objects.create(
                deployment=dep, kind=Asset.Kind.MCP_SERVER, name=name, identifier=name,
                classification=Asset.Classification.APPROVED, metadata={"effect_class": effect_class},
            ),
        )
    return stamped_under_the_rules_in_force(dep)


def _rendered(view, request, reader, **kwargs) -> bytes:
    """The bytes the route answers with, as an auditor saves them."""
    force_authenticate(request, user=reader)
    response = view(request, **kwargs)
    assert response.status_code == 200, response.status_code
    response.render()
    return response.content


def _served(dep, action: str, reader) -> bytes:
    path = {"assurance_receipt": "assurance-receipt", "signed_assurance_receipt": "signed-assurance-receipt"}
    request = APIRequestFactory().get(
        f"/api/assurance/deployments/{dep.uuid}/{path[action]}/", HTTP_ACCEPT="application/json"
    )
    return _rendered(DeploymentViewSet.as_view({"get": action}), request, reader, uuid=str(dep.uuid))


def _evidence_file(dep, reader) -> bytes:
    """What an auditor assembles from the API (specification, section 5.3): the
    deployment's findings from the finding list, and each one's uuid, fingerprint and
    evidence rows from its incident pack."""
    factory = APIRequestFactory()
    listed = json.loads(
        _rendered(
            FindingViewSet.as_view({"get": "list"}),
            factory.get("/api/assurance/findings/", {"deployment": str(dep.uuid)}, HTTP_ACCEPT="application/json"),
            reader,
        )
    )
    rows = listed["results"] if isinstance(listed, dict) else listed
    assert not (isinstance(listed, dict) and listed.get("next")), "the fixture fits one page"
    findings = []
    for row in rows:
        pack = json.loads(
            _rendered(
                FindingViewSet.as_view({"get": "incident_pack"}),
                factory.get(f"/api/assurance/findings/{row['uuid']}/incident-pack/", HTTP_ACCEPT="application/json"),
                reader,
                uuid=row["uuid"],
            )
        )
        identity = pack["identity"]["finding"]
        findings.append(
            {"uuid": identity["uuid"], "fingerprint": identity["fingerprint"], "evidence": pack["evidence"]["rows"]}
        )
    return json.dumps({"deployment": str(dep.uuid), "findings": findings}).encode()


def _edited(raw: bytes, edit) -> bytes:
    held = json.loads(raw)
    edit(held)
    return json.dumps(held).encode()


def _members_reversed(value):
    """Every object's members in reverse order. Arrays keep theirs: their order is content."""
    if isinstance(value, dict):
        return {name: _members_reversed(value[name]) for name in reversed(list(value))}
    if isinstance(value, list):
        return [_members_reversed(item) for item in value]
    return value


# ------------------------------------------------- this repository's own verification


def _class_of(refused: receipt.NotAnEnvelope) -> str:
    """``envelope_over``'s refusal, by the words it uses for each kind."""
    said = str(refused)
    if "deeper than" in said or "too deeply" in said:
        return "depth_limit"
    if "DIFFERENT document" in said:
        return "different_document"
    return "not_an_envelope"


def _backend_on_receipt(document: dict, form: str, signed_claim: bool = False) -> str | None:
    try:
        schema = receipt.receipt_schema(document.get("receipt_version"))
    except receipt.UnknownReceiptVersion:
        return "unknown_version"
    if signed_claim and document["receipt_version"] in receipt.NEVER_SIGNED:
        return "never_signed"
    defined, required = set(schema["properties"]), set(schema["required"])
    # What the signed form adds (4.1: the issue time), where this version defines it.
    signed_only = set(receipt.SIGNED_FORM_ONLY) & defined
    if form == "signed":
        defined -= set(receipt.NOT_SIGNED_OVER)
        required = (required - set(receipt.NOT_SIGNED_OVER)) | signed_only
    else:
        defined -= signed_only
    if not required <= document.keys() or not document.keys() <= defined:
        return "malformed"
    for name, rule in schema["properties"].items():
        if "const" in rule and name in document and document[name] != rule["const"]:
            return "malformed"
    # One level into each object member, and 2.0's coverage exactly one of the two
    # shapes 2.0 was emitted in.
    if shapes_read(schema, document) is None:
        return "malformed"
    # From 5.0: the authority chains, each as bad as its worst hop.
    if "authority_chains" in document and receipt.authority_chains_problem(document["authority_chains"]):
        return "malformed"
    # From 6.0: the consequential effects, read against the chains it holds.
    if "consequential_effects" in document and receipt.consequential_effects_problem(
        document["consequential_effects"], document.get("authority_chains")
    ):
        return "malformed"
    outside = ("algorithm", "digest", *receipt.NOT_SIGNED_OVER, *receipt.SIGNED_FORM_ONLY)
    hashed = {k: v for k, v in document.items() if k not in outside}
    if receipt._digest(hashed) != document["digest"]:
        return "digest_mismatch"
    return None


def _backend(artifact: bytes, *, sent: dict | None = None, evidence_of: Deployment | None = None) -> str | None:
    """This repository's answer, in the specification's step order. ``None`` is no
    refusal: every check the backend makes passed -- and a signature is not one of
    them. ``sent`` is the document the backend asked to have signed, which an
    envelope held on its own is compared with, as the route compares it."""
    text = artifact.decode("utf-8")
    if _nesting_depth(text) > MAX_JSON_DEPTH:
        return "depth_limit"
    held = json.loads(text)
    if "envelope" in held:
        envelope, document, form = held["envelope"], held["receipt"], "signed"
    elif "payloadType" in held:
        envelope, document, form = held, sent, "signed"
    else:
        envelope, document, form = None, held, "full"
    if envelope is not None:
        try:
            receipt.envelope_over(document, envelope)
        except receipt.NotAnEnvelope as refused:
            return _class_of(refused)
    answer = _backend_on_receipt(document, form, signed_claim=envelope is not None)
    if answer is None and evidence_of is not None:
        stored = receipt.deployment_receipt(
            Deployment.objects.prefetch_related("findings__evidence").get(pk=evidence_of.pk)
        )
        if (stored["digest"], stored["finding_count"]) != (
            document["evidence"]["root"],
            document["evidence"]["finding_count"],
        ):
            answer = "evidence_mismatch"
    if answer is None and envelope is None:
        # No envelope: the signed route's `envelope: null`, or the unsigned copy, whose
        # own `signed: false` (3.1 on) the schema's constant has already held it to.
        return "unsigned"
    return answer


# ---------------------------------------------------------------------- the vectors


@dataclass
class Vector:
    artifact: bytes
    backend: str | None
    keyring: bytes | None = None
    evidence: bytes | None = None
    #: The reader's freshness policy, in seconds (--max-age); None is none.
    max_age: int | None = None
    #: The verifier's clock.
    now: datetime = CHECKED
    #: A line the verdict must show.
    shows: str | None = None


@pytest.fixture
def vectors(monkeypatch):
    def engine(e):
        monkeypatch.setattr(CyberEngineClient, "from_settings", classmethod(lambda cls: e))

    # The backend's clock, held: every receipt below is issued at ISSUED.
    monkeypatch.setattr(receipt, "_utc_now", lambda: ISSUED)
    reader = _user("auditor")
    dep = _deployment(reader)
    signer, stranger = Ed25519PrivateKey.generate(), Ed25519PrivateKey.generate()
    ring = _keyring((signer, "active"))

    honest = _Engine(signer)
    engine(honest)
    signed = _served(dep, "signed_assurance_receipt", reader)
    sent = honest.sent
    assert json.loads(signed)["receipt"] == sent, "the route serves the document it had signed"
    unsigned = _served(dep, "assurance_receipt", reader)

    engine(_Engine(fails=EngineError("unreachable", kind=ENGINE_UNREACHABLE)))
    unreachable = _served(dep, "signed_assurance_receipt", reader)
    past = "[" * (MAX_JSON_DEPTH + 1) + "]" * (MAX_JSON_DEPTH + 1)
    engine(_Engine(signer, payload=past.encode()))
    too_deep_at_the_route = _served(dep, "signed_assurance_receipt", reader)

    envelope = json.loads(signed)["envelope"]
    reordered = json.dumps(_members_reversed(json.loads(unsigned)), indent=2, ensure_ascii=False).encode()
    assert reordered != unsigned and json.loads(reordered) == json.loads(unsigned)
    decision_altered = _edited(unsigned, lambda r: r["result"].update(decision="ready"))
    unknown_version = _edited(unsigned, lambda r: r.update(receipt_version="mythos.assurance.receipt/9.0"))
    member_removed = _edited(unsigned, lambda r: r.pop("coverage"))
    copy_altered = _edited(signed, lambda r: r["receipt"]["result"].update(decision="ready"))
    pack_type = json.dumps(_sign(_engine_bytes(sent), signer, "application/vnd.mythos.evidence-pack+json")).encode()
    deep_envelope = json.dumps(_sign(past.encode(), signer)).encode()
    reserialised_payload = json.dumps(json.loads(base64.b64decode(envelope["payload"])), indent=1).encode()
    reserialised = _edited(signed, lambda r: r["envelope"].update(payload=_b64(reserialised_payload)))

    # A month-old receipt dressed as a fresh one: the time moved in the envelope's
    # payload AND in the copy served beside it, so only the signature can catch it.
    moved = {**sent, "issued_at": "2026-02-01T03:04:05Z"}

    def move_the_time(answer):
        answer["envelope"]["payload"] = _b64(_engine_bytes(moved))
        answer["receipt"] = moved

    time_edited = _edited(signed, move_the_time)
    # What #118's route signed for this state: the signed form with its issue time and
    # no authority chains, under the 4.1 version string, digested by the unchanged
    # rule, signed by the key.
    four_one = {k: v for k, v in sent.items() if k not in ("authority_chains", "consequential_effects")}
    four_one["receipt_version"] = FOUR_ONE
    four_one["digest"] = receipt._digest(
        {k: v for k, v in four_one.items() if k not in ("algorithm", "digest", *receipt.SIGNED_FORM_ONLY)}
    )

    def as_four_one(answer):
        answer["envelope"] = _sign(_engine_bytes(four_one), signer)
        answer["receipt"] = four_one

    signed_four_one = _edited(signed, as_four_one)

    # A 5.0 receipt whose chain says proven while a hop of it says unproven: digested
    # again so only the verdicts disagree, which no route emits.
    def proven_over_unproven(r):
        r["authority_chains"]["chains"][0]["verdict"] = "proven"
        r["digest"] = receipt._digest({k: v for k, v in r.items() if k not in verifier.OUTSIDE_DIGEST})

    inconsistent = _edited(unsigned, proven_over_unproven)

    # What #133's route signed for this state: the signed form with no consequential
    # effects, under the 5.0 version string, digested by the unchanged rule.
    five = {k: v for k, v in sent.items() if k != "consequential_effects"}
    five["receipt_version"] = FIVE_OH
    five["digest"] = receipt._digest(
        {k: v for k, v in five.items() if k not in ("algorithm", "digest", *receipt.SIGNED_FORM_ONLY)}
    )

    def as_five(answer):
        answer["envelope"] = _sign(_engine_bytes(five), signer)
        answer["receipt"] = five

    signed_five = _edited(signed, as_five)

    # A 6.0 receipt that reads an effect covered while it names no chain: digested
    # again so only that disagrees, which no route emits.
    def covered_by_nothing(r):
        missing = next(e for e in r["consequential_effects"]["effects"] if e["status"] == "missing")
        missing["status"] = "covered"
        r["digest"] = receipt._digest({k: v for k, v in r.items() if k not in verifier.OUTSIDE_DIGEST})

    uncovered = _edited(unsigned, covered_by_nothing)

    # What a0b504a's route signed for this state: the signed form with no issue time,
    # under the 4.0 version string, digested by the unchanged rule, signed by the key.
    four = {
        k: v
        for k, v in sent.items()
        if k not in (*receipt.SIGNED_FORM_ONLY, "authority_chains", "consequential_effects")
    }
    four["receipt_version"] = FOUR_OH
    four["digest"] = receipt._digest({k: v for k, v in four.items() if k not in ("algorithm", "digest")})

    def as_four_oh(answer):
        answer["envelope"] = _sign(_engine_bytes(four), signer)
        answer["receipt"] = four

    four_oh = _edited(signed, as_four_oh)

    # The old versions, as their commits emitted them (tests/fixtures/receipts).
    def emitted(directory: str) -> bytes:
        return (RECEIPT_FIXTURES / directory / "assurance-receipt.json").read_bytes()

    as_27, as_56, as_67 = emitted("pr27-673a40b"), emitted("pr56-fdf77bf"), emitted("pr67-87e83e7")
    # #67's 2.0 receipt in its signed form, genuinely signed by the key the keyring
    # trusts and served as the signed route serves one: only its version is wrong.
    two_oh = {k: v for k, v in json.loads(as_67).items() if k != "computed_at"}
    signed_two_oh = _edited(signed, lambda r: r.update(receipt=two_oh, envelope=_sign(_engine_bytes(two_oh), signer)))

    evidence = _evidence_file(dep, reader)
    built = {
        "signed receipt": Vector(
            signed, _backend(signed), ring, shows="authority 1 chain(s) in force: 0 proven, 1 unproven, 0 broken"
        ),
        "signed receipt, its key since retired": Vector(
            signed, _backend(signed), _keyring((signer, "retired"), (stranger, "active"))
        ),
        "signed receipt, with the evidence it covers": Vector(
            signed, _backend(signed, evidence_of=dep), ring, evidence
        ),
        "unsigned copy": Vector(unsigned, _backend(unsigned)),
        "unsigned copy, members reordered and whitespace changed": Vector(reordered, _backend(reordered)),
        "signed route, the engine unreachable": Vector(unreachable, _backend(unreachable), ring),
        "signed route, the signer's payload past the depth limit (#111)": Vector(
            too_deep_at_the_route, _backend(too_deep_at_the_route), ring
        ),
        "unsigned copy, the decision altered": Vector(decision_altered, _backend(decision_altered)),
        "unsigned copy, a version nobody defined": Vector(unknown_version, _backend(unknown_version)),
        "unsigned copy, a required member removed": Vector(member_removed, _backend(member_removed)),
        "the served copy altered beside a genuine envelope": Vector(copy_altered, _backend(copy_altered), ring),
        "an evidence-pack signature presented as a receipt": Vector(pack_type, _backend(pack_type, sent=sent), ring),
        "an envelope whose payload nests past the limit": Vector(
            deep_envelope, _backend(deep_envelope, sent=sent), ring
        ),
        "checked against the wrong key": Vector(signed, _backend(signed), _keyring((stranger, "active"))),
        "signed by a key the keyring revoked": Vector(
            signed, _backend(signed), _keyring((signer, "revoked"), (stranger, "active"))
        ),
        "the signed payload re-serialised after signing": Vector(reserialised, _backend(reserialised), ring),
        "signed receipt, within --max-age, its issue time shown": Vector(
            signed, _backend(signed), ring, max_age=3600, shows=f"issued at {ISSUED_TEXT} by the issuer's clock"
        ),
        "signed receipt, its issue time edited after signing": Vector(time_edited, _backend(time_edited), ring),
        "signed receipt, issued longer ago than --max-age": Vector(
            signed, _backend(signed), ring, max_age=3600, now=ISSUED + timedelta(hours=2)
        ),
        "signed 4.1 receipt, which carries no authority chains": Vector(
            signed_four_one,
            _backend(signed_four_one),
            ring,
            shows="lacks     authority_chains: which authority chain produced each consequential effect",
        ),
        "unsigned copy, a chain reading proven over an unproven hop": Vector(inconsistent, _backend(inconsistent)),
        "signed 5.0 receipt, which carries no consequential effects": Vector(
            signed_five,
            _backend(signed_five),
            ring,
            shows="lacks     consequential_effects: which consequential effects no authority chain names",
        ),
        "unsigned copy, a consequential effect covered by no chain": Vector(uncovered, _backend(uncovered)),
        "signed 4.0 receipt, which carries no issue time": Vector(
            four_oh, _backend(four_oh), ring, shows="issued at not signed (4.0)"
        ),
        "signed 4.0 receipt under --max-age": Vector(four_oh, _backend(four_oh), ring, max_age=3600),
        "1.0 unsigned copy, as #27 emitted it": Vector(
            as_27, _backend(as_27), shows="receipt   mythos.assurance.receipt/1.0, as emitted by #27 (673a40b)"
        ),
        "2.0 unsigned copy, as #56 emitted it": Vector(
            as_56, _backend(as_56), shows="receipt   mythos.assurance.receipt/2.0, as emitted by #56 (fdf77bf)"
        ),
        "2.0 unsigned copy, as #67 emitted it": Vector(
            as_67, _backend(as_67), shows="receipt   mythos.assurance.receipt/2.0, as emitted by #67 (87e83e7)"
        ),
        "a signed claim of a 2.0 receipt, a version no route ever signed": Vector(
            signed_two_oh, _backend(signed_two_oh), ring
        ),
    }
    # Last, because it changes the stored evidence: the receipt was issued before.
    stored = Evidence.objects.get(finding__deployment=dep, content_hash="2" * 64)
    stored.content_hash = "9" * 64
    stored.save()
    built["an evidence hash altered after the receipt was issued"] = Vector(
        signed, _backend(signed, evidence_of=dep), ring, _evidence_file(dep, reader)
    )
    return built


def _answer(verdict) -> str:
    return "verified" if verdict.verified else verdict.reason


@pytest.mark.django_db
def test_every_vector_gets_the_same_answer_from_the_backend_and_the_offline_verifier(vectors):
    assert list(vectors) == [name for name, _, _ in VECTORS], "the vectors are the ones VECTORS lists"
    table, wrong = [], []
    for name, truth, verifier_only in VECTORS:
        vector = vectors[name]
        verdict = verifier.verify(
            vector.artifact, keyring=vector.keyring, evidence=vector.evidence, max_age=vector.max_age, now=vector.now
        )
        offline = _answer(verdict)
        the_verifiers_alone = verifier_only or truth == "verified"
        backend = vector.backend or (
            "no refusal; signature and age not checked here" if the_verifiers_alone else "no refusal"
        )
        table.append(f"{name:<64} backend: {backend:<48} verifier: {offline}")
        if offline != truth:
            wrong.append(f"{name}: the verifier said {offline}, the vector was built to be {truth}")
        if vector.shows is not None and vector.shows not in verdict.render():
            wrong.append(f"{name}: the verdict does not show {vector.shows!r}:\n{verdict.render()}")
        if the_verifiers_alone:
            # Every check the backend makes passed; the signature and the age are the
            # verifier's alone.
            if vector.backend is not None:
                wrong.append(f"{name}: the backend refused ({vector.backend}) where it has nothing to refuse")
        elif vector.backend != truth:
            wrong.append(f"{name}: the backend said {vector.backend}, the verifier {offline}")
    print("\n" + "\n".join(table))
    assert not wrong, "\n".join(wrong) + "\n\n" + "\n".join(table)


@pytest.mark.django_db
def test_the_digest_and_the_signed_payload_are_two_canonical_forms(vectors):
    """Section 5.1 and 6.2, on the real receipt: the digest is taken over ASCII with
    every non-ASCII character escaped; the signed payload is raw UTF-8. A verifier
    that used either form for both would pass neither test above."""
    signed = json.loads(vectors["signed receipt"].artifact)
    payload = base64.b64decode(signed["envelope"]["payload"])
    assert "Zürich".encode() in payload and b"\\u00fc" not in payload
    # The issue time is in the signed payload and outside the digest.
    assert b'"issued_at":"' + ISSUED_TEXT.encode() + b'"' in payload
    outside = ("algorithm", "digest", *receipt.SIGNED_FORM_ONLY)
    hashed = {k: v for k, v in signed["receipt"].items() if k not in outside}
    digest_form = json.dumps(hashed, sort_keys=True, separators=(",", ":")).encode()
    assert b"Z\\u00fcrich" in digest_form
    assert hashlib.sha256(digest_form).hexdigest() == signed["receipt"]["digest"] == receipt._digest(hashed)


@pytest.mark.django_db
def test_the_verifier_runs_as_a_program_from_anywhere(vectors, tmp_path):
    """``python -I``: no PYTHON* variables, no user site, and not this repository or
    the script's own directory on the path -- so a pass here is a pass with the
    standard library and ``cryptography`` alone. Exit status 0, 1 and 2."""
    def run(*files: tuple[str, bytes], flags: tuple[str, ...] = ()) -> subprocess.CompletedProcess:
        for name, data in files:
            (tmp_path / name).write_bytes(data)
        return subprocess.run(
            [sys.executable, "-I", str(VERIFIER_PATH), files[0][0], *flags],
            cwd=tmp_path, capture_output=True, text=True, timeout=60, check=False,
        )

    good = vectors["signed receipt"]
    verified = run(("signed.json", good.artifact), ("ring.json", good.keyring), flags=("--keyring", "ring.json"))
    assert verified.returncode == 0, verified.stderr
    assert verified.stdout.splitlines()[0] == "VERIFIED"
    assert "integrity and provenance only" in verified.stdout

    altered = run(("altered.json", vectors["unsigned copy, the decision altered"].artifact))
    assert altered.returncode == 1, altered.stderr
    assert altered.stdout.splitlines()[0] == "REFUSED digest_mismatch"

    no_key = run(("signed.json", good.artifact))
    assert no_key.returncode == 2 and no_key.stderr.startswith("CANNOT RUN:")
    assert no_key.stdout == ""

    public_key = next(iter(json.loads(good.keyring)["keys"].values()))["public_key"]
    by_key = run(("signed.json", good.artifact), ("key.b64", public_key.encode()), flags=("--public-key", "key.b64"))
    assert by_key.returncode == 0, by_key.stderr

    missing = run(("signed.json", good.artifact), flags=("--keyring", "nowhere.json"))
    assert missing.returncode == 2 and "cannot read nowhere.json" in missing.stderr

    # --max-age against this machine's own clock. The receipt was issued at ISSUED, in
    # the past, so a minute is too old and a century is not.
    ring = ("--keyring", "ring.json")
    stale = run(("signed.json", good.artifact), ("ring.json", good.keyring), flags=(*ring, "--max-age", "60"))
    assert stale.returncode == 1, stale.stderr
    assert stale.stdout.splitlines()[0] == "REFUSED stale"
    fresh = run(("signed.json", good.artifact), ("ring.json", good.keyring), flags=(*ring, "--max-age", "3155760000"))
    assert fresh.returncode == 0, fresh.stderr
    assert f"issued at {ISSUED_TEXT} by the issuer's clock" in fresh.stdout
    four_oh = vectors["signed 4.0 receipt under --max-age"].artifact
    untimed = run(("four.json", four_oh), ("ring.json", good.keyring), flags=(*ring, "--max-age", "3155760000"))
    assert untimed.returncode == 1, untimed.stderr
    assert untimed.stdout.splitlines()[0] == "REFUSED no_signed_time"
    negative = run(("signed.json", good.artifact), ("ring.json", good.keyring), flags=(*ring, "--max-age", "-1"))
    assert negative.returncode == 2 and negative.stderr.startswith("CANNOT RUN:")


# ------------------------------------------------------------- the lists are one list


def _spec() -> str:
    return SPEC_PATH.read_text(encoding="utf-8")


def _refusals_in_spec() -> list[str]:
    block = _spec().split("<!-- refusals -->", 1)[1].split("<!-- /refusals -->", 1)[0]
    return re.findall(r"^\| `([a-z_]+)` \|", block, flags=re.MULTILINE)


def test_the_specs_refusal_list_is_the_verifiers_and_the_vectors():
    """The completeness test. A refusal the specification lists and no vector
    exercises, or one the verifier makes that the specification does not list, fails
    here -- in whichever direction the lists drift."""
    listed = _refusals_in_spec()
    assert len(listed) == len(set(listed)), "a refusal is listed twice"
    assert set(listed) == set(verifier.REFUSALS), "the specification and the verifier list different refusals"
    exercised = {truth for _, truth, _ in VECTORS} - {"verified"}
    assert set(listed) == exercised, (
        f"refusals no vector exercises: {sorted(set(listed) - exercised)}; "
        f"vectors for refusals the specification does not list: {sorted(exercised - set(listed))}"
    )


def test_the_spec_is_the_version_the_code_emits_and_names_every_version_it_reads():
    text = _spec()
    assert receipt.RECEIPT_VERSION in text.splitlines()[0]
    assert SPEC_PATH.name in (SPEC_DIR / "README.md").read_text(encoding="utf-8")
    assert verifier.CURRENT == receipt.RECEIPT_VERSION
    assert verifier.RECEIPT_TYPE == receipt.ASSURANCE_RECEIPT_TYPE
    assert verifier.ENVELOPE_VERSION == receipt.ENVELOPE_VERSION
    assert verifier.MAX_DEPTH == MAX_JSON_DEPTH
    assert set(verifier.NOT_SIGNED) == set(receipt.NOT_SIGNED_OVER)
    assert set(verifier.SIGNED_ONLY) == set(receipt.SIGNED_FORM_ONLY)
    # The authority-chain vocabulary a 5.0 receipt is read against is the rule's own.
    from assurance import authority_chain as rule
    from assurance.models import AuthorityChain

    assert set(verifier.HOP_VERDICTS) == set(rule.HOP_VERDICTS)
    assert verifier.RELATIONS == rule.RELATIONS
    assert set(verifier.NODE_KINDS) == {k for froms, tos in rule.GRAMMAR.values() for k in (*froms, *tos)}
    assert set(verifier.CHAIN_BASES) == set(AuthorityChain.Basis.values)
    assert verifier._AUTHORITY_MEMBERS == set(receipt.RECEIPT_SCHEMA["properties"]["authority_chains"]["required"])
    # And the effect vocabulary a 6.0 receipt is read against is the rule's own.
    from assurance import consequential

    assert set(verifier.EFFECT_STATUSES) == set(consequential.STATUSES)
    assert set(verifier.EFFECT_CLASSES) == set(consequential.CLASSES)
    assert set(verifier.EFFECT_TOOL_KINDS) == set(rule.TOOL_NODE_KINDS)
    assert verifier._EFFECT_MEMBERS == set(
        receipt.RECEIPT_SCHEMA["properties"]["consequential_effects"]["required"]
    )
    # Every version the backend describes, the verifier reads -- with the members the
    # backend's own published schema for that version gives it -- and the spec names.
    versions = (receipt.RECEIPT_VERSION, *receipt.SUPERSEDED_VERSIONS)
    assert set(verifier.HASHED) == set(versions)
    for version in versions:
        properties = set(receipt.receipt_schema(version)["properties"])
        assert verifier.HASHED[version] == properties - set(verifier.OUTSIDE_DIGEST), version
        # The versions whose signed form carries an issue time are the ones whose
        # schema defines it -- no more, so a 4.0 receipt is never asked for one.
        issues = set(receipt.SIGNED_FORM_ONLY) <= properties
        assert (version in verifier._ISSUED) == issues, version
        assert f"`{version}`" in text, version

    # Who emitted each shape, what each lacks, 2.0's two coverages and the versions no
    # route ever signed: the verifier's tables are the backend's, shape for shape.
    assert set(verifier.NEVER_SIGNED) == set(receipt.NEVER_SIGNED)
    assert len(verifier.EMITTED) == len(receipt.EMITTED_AS)
    for (version, shape), emitted_as in verifier.EMITTED.items():
        key = receipt._VERSION_2_0_AS_56 if shape == "#56" else version
        assert receipt.EMITTED_AS[key] == emitted_as, (version, shape)
    branches = receipt.receipt_schema("mythos.assurance.receipt/2.0")["properties"]["coverage"]["oneOf"]
    by_pr = {branch["title"].split(" as emitted by ", 1)[1].split(" ", 1)[0]: branch for branch in branches}
    assert {pr: set(members) for pr, members in verifier.COVERAGE_2_0.items()} == {
        pr: set(branch["required"]) for pr, branch in by_pr.items()
    }
    shapes = list(verifier.EMITTED)
    for version, shape in shapes:
        said = receipt.receipt_schema(version).get("lacks", [])
        if shape == "#56":
            said = [*by_pr["#56"]["lacks"], *said]
        later = shapes[shapes.index((version, shape)) + 1:]
        assert [(list(verifier.ADDED[newer][0]), verifier.ADDED[newer][1]) for newer in later] == [
            (lack["members"], lack["means"]) for lack in said
        ], (version, shape)


def _schema_paths(schema: dict, prefix: str = "") -> list[str]:
    paths = []
    for name, rule in schema["properties"].items():
        paths.append(prefix + name)
        if "properties" in rule:
            paths.extend(_schema_paths(rule, prefix + name + "."))
    return paths


def test_the_spec_names_every_member_and_every_value_the_code_can_put_in_a_receipt():
    """Every field is documented: a member the schema gains, or a value a vocabulary
    gains, with no line in the specification fails here."""
    text = _spec()
    missing = [path for path in _schema_paths(receipt.RECEIPT_SCHEMA) if f"`{path}`" not in text]
    assert not missing, f"members the specification does not describe: {missing}"
    from assurance import authority_chain as rule
    from assurance import consequential

    values = [
        *rule.HOP_VERDICTS,
        *rule.RELATIONS,
        *(kind for froms, tos in rule.GRAMMAR.values() for kind in (*froms, *tos)),
        *rule.REASONS,
        *consequential.CLASSES,
        *consequential.STATUSES,
        *consequential.REASONS,
        *consequential.CONSEQUENTIAL_EFFECT_CLASSES,
        *consequential.READ_ONLY_EFFECT_CLASSES,
        *consequential.DESTRUCTIVE_ANNOTATIONS,
        consequential.EFFECT_SCHEMA,
        *Deployment.Decision.values,
        *Deployment.Environment.values,
        *receipt.RECEIPT_SCHEMA["properties"]["coverage"]["properties"]["verdict"]["enum"],
        *composition.CHAIN_STATUSES,
        *composition.CHAIN_BASES,
        *composition.EVIDENCE_KINDS,
        *composition.CHAIN_ROUTES,
    ]
    missing = [value for value in values if f"`{value}`" not in text]
    assert not missing, f"values the specification does not list: {missing}"


def test_the_verifier_imports_nothing_from_this_repository():
    tree = ast.parse(VERIFIER_PATH.read_text(encoding="utf-8"))
    imported = {
        alias.name.split(".")[0]
        for node in ast.walk(tree)
        if isinstance(node, ast.Import)
        for alias in node.names
    }
    imported |= {
        node.module.split(".")[0] for node in ast.walk(tree) if isinstance(node, ast.ImportFrom) and node.module
    }
    assert imported - set(sys.stdlib_module_names) == {"cryptography"}


# ------------------------------------------------------------------ backward reading


@pytest.mark.django_db
def test_every_version_the_backend_describes_is_read_and_one_it_does_not_is_refused():
    """Section 8. An older receipt is the current one without what every later version
    added -- exactly how ``receipt_schema`` derives the older schemas -- digested by the
    backend's own ``_digest``. The verifier reads each, and refuses it only for being
    unsigned, as every copy of that age is. (The genuine receipts the old commits
    emitted are vectors above, generated from git; these are derived.)

    1.0 is among them now. #27 served it, #42 replaced it, and until the receipts #27
    emitted were read back from git no registry described it: the backend refused to
    describe it and the verifier to read it. What stays refused is a version NOTHING
    emitted -- 1.2, between 1.1 and 2.0 -- by both, and never read as the nearest one."""
    reader = _user("auditor")
    current = json.loads(_served(_deployment(reader), "assurance_receipt", reader))

    def as_of(version: str, schema: dict) -> dict:
        older = {k: v for k, v in current.items() if k in schema["properties"]}
        if "coverage" in older:
            older["coverage"] = {
                k: v for k, v in older["coverage"].items() if k in schema["properties"]["coverage"]["properties"]
            }
        older["receipt_version"] = version
        older["digest"] = receipt._digest({k: v for k, v in older.items() if k not in verifier.OUTSIDE_DIGEST})
        return older

    assert "issued_at" not in current, "the full form carries no issue time: nothing signs it"
    for version in receipt.SUPERSEDED_VERSIONS:
        older = as_of(version, receipt.receipt_schema(version))
        answer = verifier.verify(json.dumps(older).encode())
        assert (answer.verified, answer.reason) == (False, "unsigned"), (version, answer.lines)
        assert _backend(json.dumps(older).encode()) == "unsigned", version

    never = as_of("mythos.assurance.receipt/1.2", receipt.receipt_schema("mythos.assurance.receipt/1.1"))
    with pytest.raises(receipt.UnknownReceiptVersion):
        receipt.receipt_schema("mythos.assurance.receipt/1.2")
    assert verifier.verify(json.dumps(never).encode()).reason == "unknown_version"
    assert _backend(json.dumps(never).encode()) == "unknown_version"
