# Generated by Django 5.2.17 on 2026-09-15 03:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FailsafeCommand",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("engine_id", models.CharField(max_length=200)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("pause", "Pause"),
                            ("resume", "Resume"),
                            ("stand_down", "Stand down"),
                            ("release", "Release"),
                            ("terminate", "Terminate"),
                        ],
                        max_length=32,
                    ),
                ),
                ("nonce", models.CharField(max_length=128, unique=True)),
                ("issued_at", models.CharField(max_length=64)),
                ("expires_at", models.CharField(max_length=64)),
                ("reason", models.TextField(blank=True, default="")),
                ("signatures", models.JSONField(blank=True, default=list)),
                ("required_signatures", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_signatures", "Awaiting signatures"),
                            ("ready", "Ready for the engine"),
                            ("consumed", "Consumed by the engine"),
                            ("expired", "Expired"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=True,
                        default="awaiting_signatures",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "initiator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drafted_failsafe_commands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FailsafeAuditEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("drafted", "Drafted"),
                            ("signed", "Signed"),
                            ("ready", "Ready"),
                            ("signature_rejected", "Signature rejected"),
                            ("served_to_engine", "Served to engine"),
                            ("consumed", "Consumed"),
                            ("expired", "Expired"),
                            ("canceled", "Canceled"),
                        ],
                        max_length=32,
                    ),
                ),
                ("detail", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="failsafe_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "command",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="failsafe.failsafecommand",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="failsafecommand",
            index=models.Index(
                fields=["engine_id", "status"], name="failsafe_fa_engine__56cef2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="failsafecommand",
            index=models.Index(
                fields=["status", "expires_at"], name="failsafe_fa_status_d03227_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="failsafeauditevent",
            index=models.Index(
                fields=["event", "timestamp"], name="failsafe_fa_event_b55786_idx"
            ),
        ),
    ]
