# Generated by Django 5.2.5 on 2026-09-27 09:04

from django.conf import settings
from django.db import migrations, models


def superseded_to_canceled(apps, schema_editor):
    """Going back: the code before this migration knows no "superseded". An
    unsigned draft set aside is closest to a cancelled one -- no longer
    signable, never served -- so it goes back as that."""
    Command = apps.get_model("failsafe", "FailsafeCommand")
    Command.objects.filter(status="superseded").update(status="canceled")


class Migration(migrations.Migration):

    dependencies = [
        ("failsafe", "0002_signed_and_stop_lane_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="failsafeauditevent",
            name="event",
            field=models.CharField(
                choices=[
                    ("drafted", "Drafted"),
                    ("signed", "Signed"),
                    ("ready", "Ready"),
                    ("signature_rejected", "Signature rejected"),
                    ("served_to_engine", "Served to engine"),
                    ("consumed", "Consumed"),
                    ("expired", "Expired"),
                    ("canceled", "Canceled"),
                    ("superseded", "Superseded by a newer draft"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="failsafecommand",
            name="status",
            field=models.CharField(
                choices=[
                    ("awaiting_signatures", "Awaiting signatures"),
                    ("ready", "Ready for the engine"),
                    ("consumed", "Consumed by the engine"),
                    ("expired", "Expired"),
                    ("canceled", "Canceled"),
                    ("superseded", "Superseded by a newer draft"),
                ],
                db_index=True,
                default="awaiting_signatures",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="failsafecommand",
            index=models.Index(
                fields=["initiator", "status", "signed", "created_at"],
                name="fsc_init_st_sig_ct",
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, superseded_to_canceled),
    ]
