# Generated by Django 5.2.5 on 2026-09-16 19:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pentest", "0016_pentestscan_verdict"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deployment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("dev", "Development"),
                            ("staging", "Staging"),
                            ("production", "Production"),
                            ("other", "Other"),
                        ],
                        default="production",
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ready", "Ready"),
                            ("ready_restricted", "Ready with restrictions"),
                            ("needs_more_evidence", "Requires additional evidence"),
                            ("needs_remediation", "Requires remediation"),
                            ("not_recommended", "Not recommended"),
                            ("paused", "Deployment paused"),
                        ],
                        db_index=True,
                        max_length=32,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "engagement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deployments",
                        to="pentest.engagement",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_deployments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("model", "Model"),
                            ("agent", "Agent"),
                            ("tool", "Tool"),
                            ("api", "API"),
                            ("gateway", "AI gateway"),
                            ("vector_db", "Vector database"),
                            ("service_account", "Service account"),
                            ("data_store", "Data store"),
                            ("mcp_server", "MCP server"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("identifier", models.CharField(blank=True, max_length=1024)),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("known", "Known"),
                            ("unmanaged", "Unmanaged"),
                            ("unknown", "Unknown"),
                            ("high_risk", "High risk"),
                            ("retired", "Retired but reachable"),
                        ],
                        default="known",
                        max_length=32,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="assurance.deployment",
                    ),
                ),
            ],
            options={
                "ordering": ["deployment", "kind", "name"],
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("fingerprint", models.CharField(db_index=True, max_length=64)),
                ("finding_type", models.CharField(max_length=128)),
                ("title", models.CharField(max_length=512)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=16,
                    ),
                ),
                ("confidence", models.FloatField(default=0.5)),
                ("cvss_score", models.FloatField(blank=True, null=True)),
                ("cvss_vector", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("triaged", "Triaged"),
                            ("remediating", "Remediating"),
                            ("retesting", "Retesting"),
                            ("closed", "Verified closed"),
                            ("accepted", "Accepted risk"),
                            ("false_positive", "False positive"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=24,
                    ),
                ),
                ("impact", models.TextField(blank=True)),
                ("business_impact", models.TextField(blank=True)),
                ("recommendation", models.TextField(blank=True)),
                ("control_mapping", models.JSONField(blank=True, default=dict)),
                ("location", models.CharField(blank=True, max_length=1024)),
                ("retest_required", models.BooleanField(default=False)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="findings",
                        to="assurance.asset",
                    ),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="assurance.deployment",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_findings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assurance_findings",
                        to="pentest.pentestscan",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("technically_verified", "Technically verified"),
                            ("configuration_verified", "Configuration verified"),
                            ("document_supported", "Document supported"),
                            ("contractually_stated", "Contractually stated"),
                            ("vendor_asserted", "Vendor asserted"),
                            ("partially_verified", "Partially verified"),
                            ("unknown", "Unknown"),
                            ("not_documented", "Not documented"),
                        ],
                        max_length=32,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, max_length=120)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="assurance.finding",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("model_provider", "Model provider"),
                            ("gateway", "AI gateway"),
                            ("embedding", "Embedding provider"),
                            ("vector_db", "Vector database"),
                            ("observability", "Observability / logging"),
                            ("cloud", "Cloud"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                (
                    "evidence_class",
                    models.CharField(
                        choices=[
                            ("technically_verified", "Technically verified"),
                            ("configuration_verified", "Configuration verified"),
                            ("document_supported", "Document supported"),
                            ("contractually_stated", "Contractually stated"),
                            ("vendor_asserted", "Vendor asserted"),
                            ("partially_verified", "Partially verified"),
                            ("unknown", "Unknown"),
                            ("not_documented", "Not documented"),
                        ],
                        default="vendor_asserted",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "kind"), name="uq_provider_name_kind"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="assurance.provider",
            ),
        ),
        migrations.AddIndex(
            model_name="deployment",
            index=models.Index(
                fields=["environment"], name="assurance_d_environ_9af646_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["deployment", "status"], name="assurance_f_deploym_0591a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["severity"], name="assurance_f_severit_cf4c67_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="finding",
            constraint=models.UniqueConstraint(
                fields=("deployment", "fingerprint"),
                name="uq_finding_deployment_fingerprint",
            ),
        ),
        migrations.AddIndex(
            model_name="evidence",
            index=models.Index(
                fields=["finding", "classification"],
                name="assurance_e_finding_195465_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["deployment", "kind"], name="assurance_a_deploym_395cd5_idx"
            ),
        ),
    ]
