# Generated by Django 5.2.5 on 2026-09-16 20:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Unknown",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("fingerprint", models.CharField(db_index=True, max_length=64)),
                ("question", models.TextField()),
                ("why_it_matters", models.TextField(blank=True)),
                ("evidence_needed", models.TextField(blank=True)),
                (
                    "deployment_impact",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigating", "Investigating"),
                            ("resolved", "Resolved"),
                            ("accepted", "Accepted as residual risk"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=24,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("derived", "Derived from a finding"),
                            ("manual", "Raised manually"),
                        ],
                        default="derived",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("review_by", models.DateField(blank=True, null=True)),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unknowns",
                        to="assurance.deployment",
                    ),
                ),
                (
                    "finding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unknowns",
                        to="assurance.finding",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_unknowns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["deployment", "status"],
                        name="assurance_u_deploym_410153_idx",
                    ),
                    models.Index(
                        fields=["deployment_impact"],
                        name="assurance_u_deploym_4d4c54_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("deployment", "fingerprint"),
                        name="uq_unknown_deployment_fingerprint",
                    )
                ],
            },
        ),
    ]
