# Generated by Django 5.2.5 on 2026-09-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0002_unknown"),
    ]

    operations = [
        migrations.AddField(
            model_name="unknown",
            name="auto_resolved",
            field=models.BooleanField(default=False),
        ),
    ]
