# Generated by Django 5.2.5 on 2026-09-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0003_unknown_auto_resolved"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.UniqueConstraint(
                fields=("deployment", "kind", "identifier"),
                name="uq_asset_deployment_kind_identifier",
            ),
        ),
    ]
