# Generated by Django 5.2.5 on 2026-09-16 23:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0004_asset_uq_asset_deployment_kind_identifier"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderAssertion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("region", "Data region"),
                            ("data_retention", "Data retention"),
                            ("logging", "Logging"),
                            ("trains_on_data", "Trains on customer data"),
                            ("subprocessors", "Subprocessors"),
                            ("certifications", "Certifications"),
                            ("dpa", "Data-processing agreement"),
                        ],
                        max_length=32,
                    ),
                ),
                ("value", models.TextField(blank=True)),
                (
                    "evidence_class",
                    models.CharField(
                        choices=[
                            ("technically_verified", "Technically verified"),
                            ("configuration_verified", "Configuration verified"),
                            ("document_supported", "Document supported"),
                            ("contractually_stated", "Contractually stated"),
                            ("vendor_asserted", "Vendor asserted"),
                            ("partially_verified", "Partially verified"),
                            ("unknown", "Unknown"),
                            ("not_documented", "Not documented"),
                        ],
                        default="vendor_asserted",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("vendor_doc", "Vendor documentation"),
                            ("contract", "Contract / DPA"),
                            ("self_declared", "Self-declared"),
                            ("measured", "Independently measured"),
                        ],
                        default="self_declared",
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assertions",
                        to="assurance.provider",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provider_assertions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["provider", "field"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "field"),
                        name="uq_provider_assertion_provider_field",
                    )
                ],
            },
        ),
    ]
