# Generated by Django 5.2.17 on 2026-09-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0005_providerassertion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="kind",
            field=models.CharField(
                choices=[
                    ("model", "Model"),
                    ("agent", "Agent"),
                    ("tool", "Tool"),
                    ("api", "API"),
                    ("gateway", "AI gateway"),
                    ("vector_db", "Vector database"),
                    ("service_account", "Service account"),
                    ("data_store", "Data store"),
                    ("mcp_server", "MCP server"),
                    ("skill", "Agent skill"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=32,
            ),
        ),
    ]
