# Generated by Django 5.2.17 on 2026-09-17 05:23
#
# Phase 2.3 — the human-reviewed remediation workflow. Adds the assignment
# (`assignee`) and review-state (`remediation_state`) fields to Finding plus the
# attributed RemediationEvent audit trail. New columns are nullable or defaulted
# so this applies to existing rows without a data-loss prompt, and the data step
# below only *seeds* the new workflow axis from the existing security disposition
# — a one-time convenience, not an ongoing coupling of the two.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


# A one-time seed for existing rows: give each finding a sensible starting
# remediation_state derived from its current security `status`. This is NOT an
# equivalence between the two axes — `status` remains the disposition and
# `remediation_state` the process — only a reasonable initial value so a
# pre-existing verified-closed finding does not start its workflow back at NEW.
_STATUS_TO_REMEDIATION_SEED = {
    "triaged": "triaged",
    "remediating": "in_progress",
    "retesting": "in_review",
    "closed": "resolved",
    "accepted": "wont_fix",
    "false_positive": "wont_fix",
}


def _seed_remediation_state(apps, schema_editor):
    """Backfill remediation_state from status for rows that predate this field.
    Only touches rows still at the default NEW, so a re-run (or a run after any
    real workflow activity) never clobbers a human-set state. ``open`` findings
    are left at the NEW default and so are not listed in the seed map."""
    Finding = apps.get_model("assurance", "Finding")
    for status, state in _STATUS_TO_REMEDIATION_SEED.items():
        Finding.objects.filter(status=status, remediation_state="new").update(
            remediation_state=state
        )


def _unseed_remediation_state(apps, schema_editor):
    """Reverse: the column is dropped when this migration is unapplied, so the
    seed leaves nothing to undo. A no-op keeps the migration cleanly reversible."""


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0007_databoundary"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_findings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="remediation_state",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("triaged", "Triaged"),
                    ("in_progress", "In progress"),
                    ("in_review", "In review"),
                    ("resolved", "Resolved"),
                    ("wont_fix", "Won't fix"),
                ],
                db_index=True,
                default="new",
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="RemediationEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "from_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "New"),
                            ("triaged", "Triaged"),
                            ("in_progress", "In progress"),
                            ("in_review", "In review"),
                            ("resolved", "Resolved"),
                            ("wont_fix", "Won't fix"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "to_state",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("triaged", "Triaged"),
                            ("in_progress", "In progress"),
                            ("in_review", "In review"),
                            ("resolved", "Resolved"),
                            ("wont_fix", "Won't fix"),
                        ],
                        max_length=24,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remediation_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remediation_events",
                        to="assurance.finding",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["finding", "created_at"],
                        name="assurance_r_finding_48c563_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(_seed_remediation_state, _unseed_remediation_state),
    ]
