# Generated by Django 5.2.5 on 2026-09-17 15:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0008_finding_remediation_workflow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssuranceClaim",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "claim_type",
                    models.CharField(
                        choices=[
                            ("data_boundary", "Data boundary"),
                            ("effective_access", "Effective access"),
                            ("ai_bom", "AI bill of materials"),
                        ],
                        max_length=32,
                    ),
                ),
                ("statement", models.TextField()),
                ("fingerprint", models.CharField(db_index=True, max_length=64)),
                ("system_fingerprint", models.CharField(max_length=64)),
                ("policy_version", models.CharField(max_length=120)),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("dev", "Development"),
                            ("staging", "Staging"),
                            ("production", "Production"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("supported", "Supported"),
                            ("verified", "Verified"),
                            ("partially_verified", "Partially verified"),
                            ("contradicted", "Contradicted"),
                            ("unknown", "Unknown"),
                            ("stale", "Stale"),
                            ("superseded", "Superseded"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "evidence_class",
                    models.CharField(
                        choices=[
                            ("technically_verified", "Technically verified"),
                            ("configuration_verified", "Configuration verified"),
                            ("document_supported", "Document supported"),
                            ("contractually_stated", "Contractually stated"),
                            ("vendor_asserted", "Vendor asserted"),
                            ("partially_verified", "Partially verified"),
                            ("unknown", "Unknown"),
                            ("not_documented", "Not documented"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("vendor_asserted", models.BooleanField(default=False)),
                (
                    "assessment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ready", "Ready"),
                            ("ready_restricted", "Ready with restrictions"),
                            ("needs_more_evidence", "Requires additional evidence"),
                            ("needs_remediation", "Requires remediation"),
                            ("not_recommended", "Not recommended"),
                            ("paused", "Deployment paused"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("supporting_summary", models.TextField(blank=True)),
                ("contradicting_summary", models.TextField(blank=True)),
                ("invalidation_conditions", models.JSONField(blank=True, default=list)),
                ("receipt_digest", models.CharField(blank=True, max_length=64)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("expiration", models.DateTimeField(blank=True, null=True)),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assurance_claims",
                        to="assurance.asset",
                    ),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assurance_claims",
                        to="assurance.deployment",
                    ),
                ),
                (
                    "human_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="assurance.assuranceclaim",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ClaimEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("draft", "Draft"),
                            ("supported", "Supported"),
                            ("verified", "Verified"),
                            ("partially_verified", "Partially verified"),
                            ("contradicted", "Contradicted"),
                            ("unknown", "Unknown"),
                            ("stale", "Stale"),
                            ("superseded", "Superseded"),
                            ("revoked", "Revoked"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("supported", "Supported"),
                            ("verified", "Verified"),
                            ("partially_verified", "Partially verified"),
                            ("contradicted", "Contradicted"),
                            ("unknown", "Unknown"),
                            ("stale", "Stale"),
                            ("superseded", "Superseded"),
                            ("revoked", "Revoked"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claim_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="assurance.assuranceclaim",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="assuranceclaim",
            index=models.Index(
                fields=["deployment", "status"], name="assurance_a_deploym_6e3f69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assuranceclaim",
            index=models.Index(
                fields=["deployment", "claim_type"],
                name="assurance_a_deploym_3f86a1_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="assuranceclaim",
            constraint=models.UniqueConstraint(
                condition=models.Q(("valid_to__isnull", True)),
                fields=("deployment", "fingerprint"),
                name="uq_current_claim",
            ),
        ),
        migrations.AddIndex(
            model_name="claimevent",
            index=models.Index(
                fields=["claim", "created_at"], name="assurance_c_claim_i_2daa84_idx"
            ),
        ),
    ]
