# Generated by Django 5.2.17 on 2026-09-17 16:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0009_assuranceclaim_claimevent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RetestRequirement",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "triggering_system_fingerprint",
                    models.CharField(blank=True, max_length=64),
                ),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opened_retest_requirements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retest_requirements",
                        to="assurance.assuranceclaim",
                    ),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retest_requirements",
                        to="assurance.deployment",
                    ),
                ),
                (
                    "resolving_claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolves_retests",
                        to="assurance.assuranceclaim",
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at"],
                "indexes": [
                    models.Index(
                        fields=["deployment", "resolved_at"],
                        name="assurance_r_deploym_47dbce_idx",
                    ),
                    models.Index(
                        fields=["claim", "resolved_at"],
                        name="assurance_r_claim_i_a327f3_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("resolved_at__isnull", True)),
                        fields=("claim",),
                        name="uq_open_retest_per_claim",
                    )
                ],
            },
        ),
    ]
