# Generated by Django 5.2.17 on 2026-09-17 18:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0010_retestrequirement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeclaredComponent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("model", "Model"),
                            ("agent", "Agent"),
                            ("tool", "Tool"),
                            ("api", "API"),
                            ("gateway", "AI gateway"),
                            ("vector_db", "Vector database"),
                            ("service_account", "Service account"),
                            ("data_store", "Data store"),
                            ("mcp_server", "MCP server"),
                            ("skill", "Agent skill"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("identifier", models.CharField(blank=True, max_length=1024)),
                ("provider_name", models.CharField(blank=True, max_length=255)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "declared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="declared_components",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declared_components",
                        to="assurance.deployment",
                    ),
                ),
            ],
            options={
                "ordering": ["deployment", "kind", "name"],
                "indexes": [
                    models.Index(
                        fields=["deployment", "kind"],
                        name="assurance_d_deploym_1aae52_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("deployment", "kind", "identifier"),
                        name="uq_declared_deployment_kind_identifier",
                    )
                ],
            },
        ),
    ]
