# Generated by Django 5.2.5 on 2026-09-18 18:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0011_declaredcomponent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectorBinding",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("endpoint", models.JSONField(blank=True, default=dict)),
                ("secret_ciphertext", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("connector", models.CharField(max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connector_bindings",
                        to="assurance.deployment",
                    ),
                ),
            ],
            options={
                "ordering": ["deployment", "connector"],
            },
        ),
        migrations.CreateModel(
            name="DispatchAttempt",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("connector", models.CharField(max_length=64)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped_inert", "Skipped — connector not configured"),
                            ("skipped_no_key", "Skipped — no encryption key"),
                            ("skipped_disabled", "Skipped — binding disabled"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("severity", "Finding severity threshold"),
                            ("blocking_decision", "Blocking decision transition"),
                            ("manual", "Manual dispatch"),
                        ],
                        max_length=32,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                (
                    "external_ref",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("attempts", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "binding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attempts",
                        to="assurance.connectorbinding",
                    ),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_attempts",
                        to="assurance.deployment",
                    ),
                ),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_attempts",
                        to="assurance.finding",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DispatchPolicy",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "min_severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="high",
                        max_length=16,
                    ),
                ),
                ("on_blocking_decision", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deployment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_policy",
                        to="assurance.deployment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostureBinding",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("endpoint", models.JSONField(blank=True, default=dict)),
                ("secret_ciphertext", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("domain", models.CharField(max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posture_bindings",
                        to="assurance.deployment",
                    ),
                ),
            ],
            options={
                "ordering": ["deployment", "domain"],
            },
        ),
        migrations.AddIndex(
            model_name="connectorbinding",
            index=models.Index(
                fields=["deployment", "connector"],
                name="assurance_c_deploym_d6db2f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="connectorbinding",
            constraint=models.UniqueConstraint(
                fields=("deployment", "connector"),
                name="uq_connector_binding_deployment",
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchattempt",
            index=models.Index(
                fields=["deployment", "outcome"], name="assurance_d_deploym_d64848_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchattempt",
            index=models.Index(
                fields=["finding", "connector"], name="assurance_d_finding_02de12_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dispatchattempt",
            constraint=models.UniqueConstraint(
                fields=("finding", "connector"),
                name="uq_dispatch_attempt_finding_connector",
            ),
        ),
        migrations.AddIndex(
            model_name="posturebinding",
            index=models.Index(
                fields=["deployment", "domain"], name="assurance_p_deploym_52ede6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="posturebinding",
            constraint=models.UniqueConstraint(
                fields=("deployment", "domain"), name="uq_posture_binding_deployment"
            ),
        ),
    ]
