# Generated by Django 5.2.5 on 2026-09-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0012_connectorbinding_dispatchattempt_dispatchpolicy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="classification_source",
            field=models.CharField(
                choices=[("machine", "Machine-derived"), ("human", "Human-set")],
                default="machine",
                max_length=16,
            ),
        ),
    ]
