# Generated by Django 5.2.17 on 2026-09-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0014_unknown_subject_alter_unknown_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="evidence_incomplete",
            field=models.BooleanField(
                default=False,
                help_text="The latest ingested scan stopped before it finished, so this deployment's decision rests on partial evidence.",
            ),
        ),
        migrations.AddField(
            model_name="deployment",
            name="last_complete_scan_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When a scan last ran to completion against this deployment.",
                null=True,
            ),
        ),
    ]
