# Generated by Django 5.2.17 on 2026-09-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0016_alter_finding_confidence_alter_finding_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="assessed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When something last assessed this asset (not merely observed it).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="assessed_by",
            field=models.CharField(
                blank=True,
                help_text="What assessed it, as the assessing engine reported itself.",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="assuranceclaim",
            name="assessment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ready", "Ready"),
                    ("ready_restricted", "Ready with restrictions"),
                    ("needs_more_evidence", "Requires additional evidence"),
                    ("audit_incomplete", "Audit incomplete"),
                    ("needs_remediation", "Requires remediation"),
                    ("not_recommended", "Not recommended"),
                    ("paused", "Deployment paused"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deployment",
            name="decision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ready", "Ready"),
                    ("ready_restricted", "Ready with restrictions"),
                    ("needs_more_evidence", "Requires additional evidence"),
                    ("audit_incomplete", "Audit incomplete"),
                    ("needs_remediation", "Requires remediation"),
                    ("not_recommended", "Not recommended"),
                    ("paused", "Deployment paused"),
                ],
                db_index=True,
                max_length=32,
                null=True,
            ),
        ),
    ]
