# Generated by Django 5.2.17 on 2026-09-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0016_alter_finding_confidence_alter_finding_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatchattempt",
            name="operation_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="dispatchattempt",
            name="policy_epoch",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="dispatchattempt",
            name="reconciled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispatchattempt",
            name="reconciled_detail",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="dispatchattempt",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("unknown", "Unknown — may have been committed"),
                    ("skipped_inert", "Skipped — connector not configured"),
                    ("skipped_no_key", "Skipped — no encryption key"),
                    ("skipped_disabled", "Skipped — binding disabled"),
                ],
                max_length=32,
            ),
        ),
    ]
