# Generated by Django 5.2.17 on 2026-09-22 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0019_bitemporal_claims"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="decision_revision",
            field=models.PositiveBigIntegerField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name="DecisionTransition",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("revision", models.PositiveBigIntegerField()),
                ("from_decision", models.CharField(blank=True, max_length=32)),
                ("to_decision", models.CharField(blank=True, max_length=32)),
                ("basis_digest", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision_transitions",
                        to="assurance.deployment",
                    ),
                ),
            ],
            options={
                "ordering": ["deployment_id", "revision"],
                "indexes": [
                    models.Index(
                        fields=["deployment", "revision"],
                        name="assurance_d_deploym_d36353_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("deployment", "revision"),
                        name="uq_decision_transition_revision",
                    )
                ],
            },
        ),
    ]
