# Generated by Django 5.2.17 on 2026-09-22 08:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0020_decision_revision_outbox"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assuranceclaim",
            name="legal_status",
            field=models.CharField(
                choices=[
                    ("legally_not_assessed", "Not legally assessed"),
                    ("legally_current", "Legally current"),
                    ("legal_review_pending", "Materiality review pending"),
                    ("legally_stale", "Legally stale"),
                ],
                db_index=True,
                default="legally_not_assessed",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="LegalObligation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("jurisdiction", models.CharField(db_index=True, max_length=64)),
                (
                    "authority_tier",
                    models.CharField(
                        choices=[
                            ("statute", "Statute"),
                            ("regulation", "Regulation"),
                            ("binding_guidance", "Binding guidance"),
                            ("case_law", "Case law"),
                            ("advisory", "Advisory guidance"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source", models.CharField(max_length=255)),
                ("source_version", models.CharField(max_length=64)),
                ("operative_date", models.DateField()),
                ("thresholds", models.JSONField(blank=True, default=dict)),
                ("exemptions", models.JSONField(blank=True, default=list)),
                (
                    "legal_review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Not reviewed"),
                            ("under_review", "Under review"),
                            ("reviewed", "Reviewed"),
                        ],
                        default="unreviewed",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deployments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="legal_obligations",
                        to="assurance.deployment",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="assurance.legalobligation",
                    ),
                ),
            ],
            options={
                "ordering": ["jurisdiction", "source", "-operative_date"],
            },
        ),
        migrations.CreateModel(
            name="MaterialityDecision",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("material", models.BooleanField()),
                ("rationale", models.TextField()),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiality_decisions",
                        to="assurance.assuranceclaim",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materiality_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiality_decisions",
                        to="assurance.legalobligation",
                    ),
                ),
            ],
            options={
                "ordering": ["-decided_at"],
            },
        ),
        migrations.AddIndex(
            model_name="legalobligation",
            index=models.Index(
                fields=["jurisdiction", "operative_date"],
                name="assurance_l_jurisdi_74590e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalobligation",
            constraint=models.UniqueConstraint(
                fields=("jurisdiction", "source", "source_version"),
                name="uq_legal_obligation_version",
            ),
        ),
        migrations.AddIndex(
            model_name="materialitydecision",
            index=models.Index(
                fields=["claim", "obligation"], name="assurance_m_claim_i_a2817f_idx"
            ),
        ),
    ]
