# Generated by Django 5.2.17 on 2026-09-22 09:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0021_legal_staleness"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LatentCondition",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            (
                                "principal_gains_capability",
                                "A named principal gains a named capability",
                            ),
                            (
                                "principal_becomes_privileged",
                                "A named principal becomes privileged",
                            ),
                            ("asset_appears", "An asset with a given name appears"),
                            (
                                "asset_becomes_unmanaged",
                                "A named asset becomes unmanaged or unknown",
                            ),
                            (
                                "boundary_allows",
                                "The data boundary starts permitting a named practice",
                            ),
                            (
                                "boundary_region_added",
                                "A named region is added to the approved boundary",
                            ),
                            (
                                "provider_posture_changes",
                                "A named provider's assertion for a named field changes",
                            ),
                            (
                                "policy_version_changes",
                                "The assurance policy in force changes",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("expected", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField()),
                ("baseline_observation", models.TextField(blank=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Declared, not yet true"),
                            ("fired", "Became true; claim invalidated"),
                            ("unobservable", "Subject can no longer be observed"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("last_evaluated_at", models.DateTimeField(blank=True, null=True)),
                ("fired_at", models.DateTimeField(blank=True, null=True)),
                ("fired_observation", models.TextField(blank=True)),
                ("declared_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="latent_conditions",
                        to="assurance.assuranceclaim",
                    ),
                ),
                (
                    "declared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="latent_conditions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="latent_conditions",
                        to="assurance.deployment",
                    ),
                ),
                (
                    "fired_requirement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fired_by_conditions",
                        to="assurance.retestrequirement",
                    ),
                ),
            ],
            options={
                "ordering": ["-declared_at"],
                "indexes": [
                    models.Index(
                        fields=["deployment", "state"],
                        name="assurance_l_deploym_b463d8_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("claim", "kind", "subject", "expected"),
                        name="uq_latent_condition_declaration",
                    )
                ],
            },
        ),
    ]
