# Generated by Django 5.2.17 on 2026-09-22 15:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0022_latent_conditions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unknown",
            name="source",
            field=models.CharField(
                choices=[
                    ("derived", "Derived from a finding"),
                    ("posture", "Derived from an undeclared provider posture"),
                    ("chain", "Raised by the chain birth registry"),
                    ("manual", "Raised manually"),
                ],
                default="derived",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="ChainBirth",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("chain", models.CharField(max_length=64)),
                ("birth_id", models.CharField(max_length=128)),
                ("born_at", models.CharField(blank=True, max_length=64)),
                ("first_registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("highest_seq", models.IntegerField(blank=True, null=True)),
                ("rebirth_seen_at", models.DateTimeField(blank=True, null=True)),
                ("rebirth_birth_id", models.CharField(blank=True, max_length=128)),
                ("rebirth_count", models.IntegerField(default=0)),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chain_births",
                        to="assurance.deployment",
                    ),
                ),
            ],
            options={
                "ordering": ["deployment", "chain"],
                "indexes": [
                    models.Index(
                        fields=["deployment", "rebirth_seen_at"],
                        name="assurance_c_deploym_77f241_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("deployment", "chain"), name="uq_chain_birth_per_chain"
                    )
                ],
            },
        ),
    ]
