# Generated by Django 5.2.17 on 2026-09-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0024_deployment_check_coverage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="latentcondition",
            name="kind",
            field=models.CharField(
                choices=[
                    (
                        "principal_gains_capability",
                        "A named principal gains a named capability",
                    ),
                    (
                        "principal_becomes_privileged",
                        "A named principal becomes privileged",
                    ),
                    ("asset_appears", "An asset with a given name appears"),
                    (
                        "asset_becomes_unmanaged",
                        "A named asset stops being governed (unmanaged, unknown, high risk or retired)",
                    ),
                    (
                        "boundary_allows",
                        "The data boundary starts permitting a named practice",
                    ),
                    (
                        "boundary_region_added",
                        "A named region is added to the approved boundary",
                    ),
                    (
                        "provider_posture_changes",
                        "A named provider's assertion for a named field changes",
                    ),
                    ("policy_version_changes", "The assurance policy in force changes"),
                ],
                max_length=40,
            ),
        ),
    ]
