# Generated by Django 5.2.17 on 2026-09-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0026_null_the_invented_drift_confidence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispatchattempt",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("unknown", "Unknown — may have been committed"),
                    ("skipped_inert", "Skipped — connector not configured"),
                    ("skipped_no_key", "Skipped — no encryption key"),
                    ("skipped_disabled", "Skipped — binding disabled"),
                    (
                        "skipped_epoch_moved",
                        "Skipped — authorized under an authority that has since changed",
                    ),
                ],
                max_length=32,
            ),
        ),
    ]
