# Generated by Django 5.2.17 on 2026-09-23 18:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0027_enforce_the_dispatch_policy_epoch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovedWorkflow",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("slug", models.SlugField(max_length=200)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approved_workflows",
                        to="assurance.deployment",
                    ),
                ),
            ],
            options={
                "ordering": ["deployment", "slug"],
                "indexes": [
                    models.Index(
                        fields=["deployment"], name="assurance_a_deploym_82497f_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("deployment", "slug"),
                        name="uq_approved_workflow_deployment_slug",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowChainOutcome",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("workflow", models.SlugField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("held", "Held — the chain was exercised and it holds"),
                            ("violated", "Violated — exercised, and does not hold"),
                            (
                                "not_demonstrated",
                                "Not demonstrated — exercised, evidence thin",
                            ),
                            ("incomplete", "Incomplete — not fully exercised"),
                        ],
                        max_length=32,
                    ),
                ),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chain_outcomes",
                        to="assurance.deployment",
                    ),
                ),
            ],
            options={
                "ordering": [
                    models.OrderBy(
                        models.F("observed_at"), descending=True, nulls_last=True
                    ),
                    "-created_at",
                ],
                "indexes": [
                    models.Index(
                        fields=["deployment", "workflow"],
                        name="assurance_w_deploym_a92666_idx",
                    ),
                    models.Index(
                        fields=["deployment", "status"],
                        name="assurance_w_deploym_f7611f_idx",
                    ),
                ],
            },
        ),
    ]
