# Generated by Django 5.2.17 on 2026-09-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0028_the_composition_rule_nobody_consulted"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowchainoutcome",
            name="basis",
            field=models.CharField(
                choices=[
                    ("demonstrated", "Demonstrated — a run produced this outcome"),
                    ("attested", "Attested — a person asserted it"),
                    ("unknown", "Unknown — the record does not say"),
                ],
                default="unknown",
                max_length=32,
            ),
        ),
    ]
