# Generated by Django 5.2.17 on 2026-09-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0029_a_status_that_claims_an_exercise"),
    ]

    operations = [
        migrations.AddField(
            model_name="assuranceclaim",
            name="input_fingerprint",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
