# Generated by Django 5.2.17 on 2026-09-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0030_per_claim_input_fingerprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="retestrequirement",
            name="claim_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
