# Generated by Django 5.2.17 on 2026-09-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    """Record which outcome keyring a stored decision was computed under.

    NULL on every existing row, which is what marks a decision as computed before
    the signed-outcome rule: 0032 demoted every typed-in ``demonstrated`` row to
    ``attested``, and an approved workflow's attested ``held`` now floors at
    NEEDS_MORE_EVIDENCE, so a stored READY computed from typed-in chains is stale.

    The recompute is not done here -- it needs the live decision rule over live
    models, which a migration must not import. It is done by
    :func:`assurance.signals.recompute_decisions_computed_under_another_rule` after
    every ``migrate``, for rows still NULL: idempotent, so a ``migrate`` that stops
    after this migration and is re-run still recomputes them. And a reader of a
    NULL-stamped decision reconciles it first (``decision.current_decision``).
    """

    dependencies = [
        ("assurance", "0032_signed_chain_outcomes"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="decision_keyring",
            field=models.CharField(
                blank=True, default=None, editable=False, max_length=64, null=True
            ),
        ),
    ]
