# Generated by Django 5.2.5 on 2026-09-26 20:55

from django.db import migrations, models


def _no_sending_attempts(apps, schema_editor):
    """Refuse to go back past this migration while any attempt is SENDING.

    Code from before it does not know SENDING: it reads such an attempt as neither
    sent nor uncertain, and pushes it again -- blind, though the request may have
    landed. Settle them first: let a run finish (they resolve by looking, or by
    `manage.py reconcile_dispatch_attempt`), then roll back."""
    DispatchAttempt = apps.get_model("assurance", "DispatchAttempt")
    sending = DispatchAttempt.objects.filter(outcome="sending").count()
    if sending:
        raise RuntimeError(
            f"{sending} dispatch attempt(s) are 'sending': code before 0042 would push them again blind. "
            "Settle them first (manage.py retry_blocking_dispatches, or reconcile_dispatch_attempt), "
            "then migrate back."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0041_decision_dispatch_claim"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispatchattempt",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("unknown", "Unknown — may have been committed"),
                    ("sending", "Sending — no answer recorded yet"),
                    ("skipped_inert", "Skipped — connector not configured"),
                    ("skipped_no_key", "Skipped — no encryption key"),
                    ("skipped_disabled", "Skipped — binding disabled"),
                    (
                        "skipped_epoch_moved",
                        "Skipped — authorized under an authority that has since changed",
                    ),
                ],
                max_length=32,
            ),
        ),
        # Backwards, this runs first: nothing is unapplied while an attempt is SENDING.
        migrations.RunPython(migrations.RunPython.noop, _no_sending_attempts),
    ]
