# Generated by Django 5.2.5 on 2026-09-27 01:03

import secrets

import django.utils.timezone
from django.db import migrations, models


def _create_installation(apps, schema_editor):
    """This installation's random identity and marker secret, generated once. Never
    derived from SECRET_KEY: rotating that key must change no marker."""
    AssuranceInstallation = apps.get_model("assurance", "AssuranceInstallation")
    AssuranceInstallation.objects.get_or_create(
        pk=1,
        defaults={"installation_id": secrets.token_hex(16), "marker_secret": secrets.token_hex(32)},
    )


def _back_to_0042(apps, schema_editor):
    """Refuse to go back while an uncertain attempt carries a marker only this
    migration's code can look for; otherwise record SENT_TO_CLOSED as SENT.

    Code before 0043 looks for another label, finds nothing, and after five minutes
    reads "nothing" as licence to push again -- a second ticket. Settle them first
    (a run looks for them; or `manage.py reconcile_dispatch_attempt`). SENT_TO_CLOSED
    is SENT to that code: the issue exists, closed."""
    DispatchAttempt = apps.get_model("assurance", "DispatchAttempt")
    held = DispatchAttempt.objects.filter(outcome__in=("unknown", "sending"), marker_version__isnull=False).count()
    if held:
        raise RuntimeError(
            f"{held} uncertain dispatch attempt(s) carry a marker that code before 0043 cannot look for; it "
            "would push them again. Settle them first (manage.py retry_blocking_dispatches, or "
            "reconcile_dispatch_attempt), then migrate back."
        )
    DispatchAttempt.objects.filter(outcome="sent_to_closed").update(outcome="sent")


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0042_dispatch_attempt_sending"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssuranceInstallation",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("installation_id", models.CharField(max_length=64)),
                ("marker_secret", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name="dispatchattempt",
            name="marker",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="dispatchattempt",
            name="marker_version",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dispatchattempt",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("sent", "Sent"),
                    ("sent_to_closed", "Sent — to an issue the tracker has closed"),
                    ("failed", "Failed"),
                    ("unknown", "Unknown — may have been committed"),
                    ("sending", "Sending — no answer recorded yet"),
                    ("skipped_inert", "Skipped — connector not configured"),
                    ("skipped_no_key", "Skipped — no encryption key"),
                    ("skipped_disabled", "Skipped — binding disabled"),
                    (
                        "skipped_epoch_moved",
                        "Skipped — authorized under an authority that has since changed",
                    ),
                ],
                max_length=32,
            ),
        ),
        migrations.RunPython(_create_installation, migrations.RunPython.noop),
        # Backwards, this runs first.
        migrations.RunPython(migrations.RunPython.noop, _back_to_0042),
    ]
