# Generated by Django 5.2.5 on 2026-09-28 14:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0043_dispatch_markers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assuranceclaim",
            name="evidence_audit",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="assuranceclaim",
            name="evidence_verdict",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pass", "Pass"),
                    ("fail", "Fail"),
                    ("incomplete", "Incomplete"),
                    ("contested", "Contested"),
                    ("insufficient_evidence", "Insufficient evidence"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="claimevent",
            name="cause",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.CreateModel(
            name="ClaimEvidence",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("claim_fingerprint", models.CharField(db_index=True, max_length=64)),
                ("subject_deployment", models.CharField(blank=True, max_length=64)),
                ("subject_claim_type", models.CharField(blank=True, max_length=32)),
                ("subject_asset", models.CharField(blank=True, max_length=64)),
                ("subject_route", models.CharField(blank=True, max_length=64)),
                ("subject_inputs", models.CharField(blank=True, max_length=64)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("independent", "Independent observer"),
                            ("operator", "Deploying organisation's operator"),
                            ("vendor", "Vendor / provider"),
                            ("target", "The system under assurance itself"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("signer", models.CharField(blank=True, max_length=255)),
                ("signature_verified", models.BooleanField(default=False)),
                ("content_digest", models.CharField(blank=True, max_length=128)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("incomplete", "Incomplete"),
                            ("contested", "Contested"),
                            ("insufficient_evidence", "Insufficient evidence"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "evidence_class",
                    models.CharField(
                        choices=[
                            ("technically_verified", "Technically verified"),
                            ("configuration_verified", "Configuration verified"),
                            ("document_supported", "Document supported"),
                            ("contractually_stated", "Contractually stated"),
                            ("vendor_asserted", "Vendor asserted"),
                            ("partially_verified", "Partially verified"),
                            ("unknown", "Unknown"),
                            ("not_documented", "Not documented"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                ("state_check_ref", models.CharField(blank=True, max_length=255)),
                ("state_checked_at", models.DateTimeField(blank=True, null=True)),
                ("conditions", models.JSONField(blank=True, default=list)),
                ("residual_uncertainty", models.JSONField(blank=True, default=list)),
                ("expires_at", models.DateTimeField()),
                ("invalidated_at", models.DateTimeField(blank=True, null=True)),
                ("invalidation_reason", models.TextField(blank=True)),
                ("actor_account", models.CharField(blank=True, max_length=255)),
                (
                    "actor_account_kind",
                    models.CharField(
                        choices=[
                            ("human_user", "Account registered to a person"),
                            ("service_account", "Service account"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("actor_device", models.CharField(blank=True, max_length=255)),
                ("actor_organization", models.CharField(blank=True, max_length=255)),
                ("actor_human", models.CharField(blank=True, max_length=255)),
                ("human_identified_by", models.CharField(blank=True, max_length=255)),
                ("areas", models.JSONField(blank=True, default=dict)),
                ("summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_evidence",
                        to="assurance.deployment",
                    ),
                ),
                (
                    "invalidated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recorded_against",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="assurance.assuranceclaim",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="assurance.claimevidence",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
                "indexes": [
                    models.Index(
                        fields=["deployment", "claim_fingerprint"],
                        name="assurance_c_deploym_8de2fd_idx",
                    )
                ],
            },
        ),
    ]
