# Generated by Django 5.2.5 on 2026-09-28 17:26

from django.db import migrations, models


def _snapshot_invalidators(apps, schema_editor):
    """An item invalidated before the snapshot existed takes the name of the account
    that invalidated it, while that account is still there to read. One whose
    account is already gone has no attribution left to copy, and now reads as the
    unattributed invalidation it is: it retires nothing until a person invalidates
    it again."""
    ClaimEvidence = apps.get_model("assurance", "ClaimEvidence")
    rows = ClaimEvidence.objects.filter(invalidated_by__isnull=False, invalidated_by_username="").select_related(
        "invalidated_by"
    )
    for row in rows.iterator():
        row.invalidated_by_username = (row.invalidated_by.username or "")[:150]
        row.save(update_fields=["invalidated_by_username"])


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0044_claim_evidence_audit"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimevidence",
            name="invalidated_by_username",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=150
            ),
        ),
        migrations.RunPython(_snapshot_invalidators, migrations.RunPython.noop),
    ]
