# Generated by Django 5.2.5 on 2026-09-29 03:59

import django.db.models.deletion
from django.db import migrations, models


def _snapshot_the_persons(apps, schema_editor):
    """Every event an account made before the snapshot existed is a person's, and
    takes the name of that account while it is still there to read. An event whose
    account is already gone has nothing left to copy: it reads as the machine's,
    as it did before this migration -- the loss this snapshot stops from now on."""
    ClaimEvent = apps.get_model("assurance", "ClaimEvent")
    rows = ClaimEvent.objects.filter(actor__isnull=False).select_related("actor")
    for row in rows.iterator():
        row.by_person = True
        row.actor_username = (row.actor.username or "")[:150]
        row.save(update_fields=["by_person", "actor_username"])


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0046_claim_audit_weighing"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimevent",
            name="actor_username",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=150
            ),
        ),
        migrations.AddField(
            model_name="claimevent",
            name="by_person",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="claimevent",
            name="carried_from",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="assurance.claimevent",
            ),
        ),
        # Backwards the three columns are dropped: nothing to put back.
        migrations.RunPython(_snapshot_the_persons, migrations.RunPython.noop),
    ]
