# Generated by Django 5.2.5 on 2026-10-05 14:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0048_claim_confidence_follows_its_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RetestClosureEvidence",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("fixtures", models.JSONField(blank=True, default=dict)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("independent", "Independent observer"),
                            ("operator", "Deploying organisation's operator"),
                            ("vendor", "Vendor / provider"),
                            ("target", "The system under assurance itself"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("content_digest", models.CharField(blank=True, max_length=128)),
                ("summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closure_evidence",
                        to="assurance.finding",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
                "indexes": [
                    models.Index(
                        fields=["finding", "created_at"],
                        name="assurance_r_finding_c8077e_idx",
                    )
                ],
            },
        ),
    ]
