# Generated by Django 5.2.5 on 2026-10-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0049_retest_closure_evidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="retestclosureevidence",
            name="document",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
