# Generated by Django 5.2.5 on 2026-10-06 21:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0050_retest_closure_evidence_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClosureEvidenceForward",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Queued, not yet sent"),
                            ("sending", "Being sent"),
                            ("sent", "Recorded by Minotaur"),
                            ("failed", "Certainly not recorded; retried"),
                            (
                                "unknown",
                                "May have been recorded; retried only when asked",
                            ),
                            ("refused", "Minotaur cannot read it; never retried"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("dataset_row_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forward",
                        to="assurance.retestclosureevidence",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "updated_at"],
                        name="assurance_c_status_c19c9c_idx",
                    )
                ],
            },
        ),
    ]
