# Generated by Django 5.2.5 on 2026-10-07 04:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0054_repair_contract"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorityChain",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("workflow", models.SlugField(max_length=200)),
                ("effect", models.CharField(max_length=200)),
                ("hops", models.JSONField(default=list)),
                ("digest", models.CharField(max_length=71)),
                (
                    "gate_outcome_id",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "effect_outcome_id",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "route_fingerprint",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            (
                                "demonstrated",
                                "Demonstrated — an engine signed this chain",
                            ),
                            ("attested", "Attested — a person recorded it"),
                        ],
                        default="attested",
                        max_length=32,
                    ),
                ),
                (
                    "outcome_id",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                ("observer_engine", models.CharField(blank=True, max_length=64)),
                ("observer_key_id", models.CharField(blank=True, max_length=64)),
                ("envelope", models.JSONField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("note", models.TextField(blank=True)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authority_chains",
                        to="assurance.deployment",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authority_chains",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["deployment", "id"],
                "indexes": [
                    models.Index(
                        fields=["deployment", "workflow", "effect"],
                        name="assurance_authchain_effect",
                    )
                ],
            },
        ),
    ]
