# Generated by Django 5.2.5 on 2026-10-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0055_authority_chains"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowchainoutcome",
            name="effect_dispatch_id",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="workflowchainoutcome",
            name="effect_evidence",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
