# Generated by Django 5.2.5 on 2026-10-07 15:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0056_observed_effect_evidence"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentityEvidence",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            (
                                "authentication",
                                "Authentication — a person signed in as a principal",
                            ),
                            (
                                "delegation",
                                "Delegation — a principal delegated a scope to an agent",
                            ),
                        ],
                        max_length=32,
                    ),
                ),
                ("outcome_id", models.CharField(max_length=32, unique=True)),
                ("observer_engine", models.CharField(max_length=64)),
                ("observer_key_id", models.CharField(max_length=64)),
                ("evidence_digest", models.CharField(max_length=71)),
                ("envelope", models.JSONField()),
                ("document", models.JSONField()),
                ("replay_key", models.CharField(max_length=160, unique=True)),
                ("principal", models.CharField(max_length=200)),
                ("witness", models.CharField(max_length=32)),
                ("observed_at", models.DateTimeField()),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_evidence",
                        to="assurance.deployment",
                    ),
                ),
            ],
            options={
                "ordering": ["deployment", "id"],
                "indexes": [
                    models.Index(
                        fields=["deployment", "principal"],
                        name="assurance_identity_principal",
                    )
                ],
            },
        ),
    ]
