# Generated by Django 5.2.5 on 2026-10-07 16:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0057_identity_evidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowchainoutcome",
            name="dispatch_route_fingerprint",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=64
            ),
        ),
        migrations.CreateModel(
            name="ApprovalVersion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("workflow", models.SlugField(max_length=200)),
                ("digest", models.CharField(blank=True, max_length=64)),
                ("tools", models.JSONField(default=list)),
                ("in_force_from", models.DateTimeField()),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_versions",
                        to="assurance.deployment",
                    ),
                ),
            ],
            options={
                "ordering": ["deployment", "workflow", "in_force_from", "id"],
                "indexes": [
                    models.Index(
                        fields=["deployment", "workflow", "in_force_from"],
                        name="assurance_approval_version",
                    )
                ],
            },
        ),
    ]
