# Generated by Django 5.2.5 on 2026-10-08 03:06
#
# The graph edges an authority chain's through_identity, performs and reach are read
# against, as of dispatch (assurance.edge_history). Nothing is backfilled: no history
# of the graph existed, so a deployment's history begins at its first note (an asset
# write, or the next decision refresh), and a dispatch before that reads unrecorded.

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0058_dispatch_epoch"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorityEdgeVersion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("identity", "identity"),
                            ("action", "action"),
                            ("reach", "reach"),
                            ("begun", "begun"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=64)),
                ("target", models.TextField(blank=True)),
                ("in_force", models.BooleanField()),
                ("noticed_at", models.DateTimeField()),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authority_edge_versions",
                        to="assurance.deployment",
                    ),
                ),
            ],
            options={
                "ordering": ["deployment", "noticed_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["deployment", "kind", "source"],
                        name="assurance_edge_version",
                    )
                ],
            },
        ),
    ]
