# Generated by Django 5.2.5 on 2026-10-08 10:34
#
# SPINE Economic Exposure, phase E0 (docs/economics/spec-v1.md): the financial
# sources, the model inventory, and the scenario, review and override records the
# separation rules are enforced on (assurance.economics.models). New, empty tables
# only: nothing is backfilled, and nothing reads or writes them yet.

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0059_graph_edge_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialScenario",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("system_fingerprint", models.CharField(blank=True, max_length=64)),
                ("causal_effect", models.CharField(blank=True, max_length=71)),
                (
                    "author_username",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=150
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="economics_scenarios_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_scenarios",
                        to="assurance.deployment",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by",
                        to="assurance.financialscenario",
                    ),
                ),
            ],
            options={
                "ordering": ["deployment", "id"],
            },
        ),
        migrations.CreateModel(
            name="FinancialSource",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("source_key", models.SlugField(max_length=200)),
                ("version", models.PositiveIntegerField()),
                ("provider", models.CharField(max_length=200)),
                ("dataset", models.CharField(max_length=200)),
                ("url", models.URLField(blank=True, max_length=2048)),
                (
                    "license_class",
                    models.CharField(
                        choices=[
                            ("unreviewed", "unreviewed"),
                            ("open", "open"),
                            ("restricted", "restricted"),
                            ("licensed", "licensed"),
                            ("customer", "customer"),
                        ],
                        default="unreviewed",
                        max_length=32,
                    ),
                ),
                (
                    "trust_tier",
                    models.CharField(
                        choices=[
                            ("authoritative", "authoritative"),
                            ("customer", "customer"),
                            ("licensed_vendor", "licensed_vendor"),
                            ("benchmark", "benchmark"),
                            ("unverified", "unverified"),
                        ],
                        default="unverified",
                        max_length=32,
                    ),
                ),
                ("retrieved_at", models.DateTimeField()),
                ("snapshot_hash", models.CharField(max_length=71)),
                ("schema_version", models.CharField(max_length=64)),
                (
                    "recorded_by_username",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=150
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_sources",
                        to="assurance.deployment",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="economics_sources_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["source_key", "version", "id"],
            },
        ),
        migrations.CreateModel(
            name="ModelInventoryEntry",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("model_id", models.SlugField(max_length=200)),
                ("version", models.CharField(max_length=64)),
                ("revision", models.PositiveIntegerField()),
                ("owner", models.CharField(max_length=200)),
                ("intended_use", models.TextField()),
                ("limitations", models.TextField()),
                ("retirement_date", models.DateField(blank=True, null=True)),
                (
                    "recorded_by_username",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=150
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="economics_inventory_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "model inventory entries",
                "ordering": ["model_id", "version", "revision"],
            },
        ),
        migrations.CreateModel(
            name="ScenarioReview",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "reviewer_username",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=150
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("returned", "Returned to the author"),
                        ],
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "reviewed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="economics_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="assurance.financialscenario",
                    ),
                ),
            ],
            options={
                "ordering": ["scenario", "id"],
            },
        ),
        migrations.CreateModel(
            name="SensitiveOverride",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("subject", models.CharField(max_length=200)),
                ("reason", models.TextField()),
                (
                    "requested_by_username",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=150
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="economics_overrides_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensitive_overrides",
                        to="assurance.financialscenario",
                    ),
                ),
            ],
            options={
                "ordering": ["scenario", "id"],
            },
        ),
        migrations.CreateModel(
            name="OverrideApproval",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "approver_username",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=150
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="economics_override_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "override",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="assurance.sensitiveoverride",
                    ),
                ),
            ],
            options={
                "ordering": ["override", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="financialscenario",
            index=models.Index(
                fields=["deployment"], name="assurance_econ_scenario_dep"
            ),
        ),
        migrations.AddIndex(
            model_name="financialsource",
            index=models.Index(
                fields=["deployment", "source_key"], name="assurance_econ_source_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="financialsource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deployment__isnull", True)),
                fields=("source_key", "version"),
                name="uq_econ_source_platform_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="financialsource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deployment__isnull", False)),
                fields=("deployment", "source_key", "version"),
                name="uq_econ_source_tenant_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="financialsource",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="ck_econ_source_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="modelinventoryentry",
            constraint=models.UniqueConstraint(
                fields=("model_id", "version", "revision"),
                name="uq_econ_inventory_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="modelinventoryentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)),
                name="ck_econ_inventory_revision_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="overrideapproval",
            constraint=models.UniqueConstraint(
                condition=models.Q(("approver__isnull", False)),
                fields=("override", "approver"),
                name="uq_econ_override_one_approval_each",
            ),
        ),
    ]
