# Generated by Django 5.2.5 on 2026-10-08 13:34
#
# SPINE Economic Exposure, phase E1 (docs/economics/spec-v1.md, sections 11 to
# 13): the FX and cost-index observations a source version's snapshot holds
# (assurance.economics.models.FXObservation and CostIndexObservation), and
# FinancialSource.synthetic, which keeps made-up test data out of every
# production run and below unverified. New, empty tables and a column defaulting
# to False: nothing is backfilled, and only the snapshot loader an operator runs
# writes the observations. Both observation tables are append-only and go with
# their source (CASCADE), which goes with its deployment. Neither has an account
# column, so removing an operator never writes them, and no check constraint
# names a column a cascade or a SET_NULL writes.

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0060_economic_exposure_foundations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CostIndexObservation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("series_id", models.CharField(max_length=100)),
                ("geography", models.CharField(max_length=32)),
                ("category", models.CharField(max_length=200)),
                ("base", models.CharField(max_length=64)),
                ("period", models.CharField(max_length=7)),
                ("value", models.DecimalField(decimal_places=6, max_digits=15)),
                ("vintage_date", models.DateField()),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "cost index observation",
                "ordering": ["source", "series_id", "period", "vintage_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="FXObservation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("base_currency", models.CharField(max_length=3)),
                ("quote_currency", models.CharField(max_length=3)),
                ("rate", models.DecimalField(decimal_places=9, max_digits=15)),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("reference", "reference"),
                            ("mid", "mid"),
                            ("bid", "bid"),
                            ("ask", "ask"),
                        ],
                        max_length=16,
                    ),
                ),
                ("provider", models.CharField(max_length=200)),
                ("observed_at", models.DateTimeField()),
                ("effective_date", models.DateField()),
                ("source_snapshot_hash", models.CharField(max_length=71)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "FX observation",
                "ordering": [
                    "source",
                    "provider",
                    "base_currency",
                    "quote_currency",
                    "rate_type",
                    "effective_date",
                    "id",
                ],
            },
        ),
        migrations.AddField(
            model_name="financialsource",
            name="synthetic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="financialsource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("synthetic", False), ("trust_tier", "unverified"), _connector="OR"
                ),
                name="ck_econ_source_synthetic_unverified",
            ),
        ),
        migrations.AddField(
            model_name="costindexobservation",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cost_index_observations",
                to="assurance.financialsource",
            ),
        ),
        migrations.AddField(
            model_name="fxobservation",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fx_observations",
                to="assurance.financialsource",
            ),
        ),
        migrations.AddConstraint(
            model_name="costindexobservation",
            constraint=models.UniqueConstraint(
                fields=("source", "series_id", "period", "vintage_date"),
                name="uq_econ_cost_index_observation",
            ),
        ),
        migrations.AddConstraint(
            model_name="costindexobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__gt", 0)), name="ck_econ_cost_index_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="fxobservation",
            index=models.Index(
                fields=["base_currency", "quote_currency", "effective_date"],
                name="assurance_econ_fx_pair_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="fxobservation",
            constraint=models.UniqueConstraint(
                fields=(
                    "source",
                    "provider",
                    "base_currency",
                    "quote_currency",
                    "rate_type",
                    "effective_date",
                ),
                name="uq_econ_fx_observation",
            ),
        ),
        migrations.AddConstraint(
            model_name="fxobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("rate__gt", 0)), name="ck_econ_fx_rate_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="fxobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rate_type__in", ["reference", "mid", "bid", "ask"])
                ),
                name="ck_econ_fx_rate_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="fxobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("base_currency", models.F("quote_currency")), _negated=True
                ),
                name="ck_econ_fx_pair",
            ),
        ),
    ]
