# Generated by Django 5.2.5 on 2026-10-08 15:26
#
# SPINE Economic Exposure, the scenario engine (docs/economics/spec-v1.md,
# sections 19 and 20): the customer parameter set and its versions
# (CustomerParameterSet), the financial parameters of a scenario or a set version
# (FinancialParameter), and a scenario's loss events and their components
# (LossEvent, LossComponent). New, empty tables: nothing is backfilled. All four
# are append-only and go with their deployment (CASCADE through the scenario or
# the set). The one account column, CustomerParameterSet.author, is SET_NULL, and
# no check constraint names it, so removing an operator -- a stop -- is never held
# back; no constraint names a column a cascade or a SET_NULL writes.

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0061_fx_and_cost_index_observations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerParameterSet",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("set_key", models.SlugField(max_length=100)),
                ("version", models.PositiveIntegerField()),
                (
                    "schema_version",
                    models.CharField(
                        default="mythos.economics.parameter-set/v1", max_length=64
                    ),
                ),
                ("insurance_exclusions", models.JSONField(blank=True, default=list)),
                ("variable_count", models.PositiveIntegerField()),
                ("content_digest", models.CharField(max_length=71)),
                (
                    "author_username",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=150
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="economics_parameter_sets_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_parameter_sets",
                        to="assurance.deployment",
                    ),
                ),
            ],
            options={
                "ordering": ["deployment", "set_key", "version", "id"],
            },
        ),
        migrations.CreateModel(
            name="FinancialParameter",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("money", "money"),
                            ("money_per_unit", "money_per_unit"),
                            ("money_per_hour", "money_per_hour"),
                            ("money_per_year", "money_per_year"),
                            ("count", "count"),
                            ("count_per_day", "count_per_day"),
                            ("ratio", "ratio"),
                            ("hours", "hours"),
                            ("days", "days"),
                            ("years", "years"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("CUSTOMER_PROVIDED", "CUSTOMER_PROVIDED"),
                            ("MYTHOS_OBSERVED", "MYTHOS_OBSERVED"),
                            ("CALCULATED", "CALCULATED"),
                            ("OFFICIAL_PUBLIC", "OFFICIAL_PUBLIC"),
                            ("LICENSED_MARKET", "LICENSED_MARKET"),
                            ("INDUSTRY_BENCHMARK", "INDUSTRY_BENCHMARK"),
                            ("EXPERT_ESTIMATE", "EXPERT_ESTIMATE"),
                            ("UNKNOWN", "UNKNOWN"),
                        ],
                        max_length=32,
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("low", models.TextField()),
                ("base", models.TextField()),
                ("high", models.TextField()),
                ("evidence_ref", models.CharField(max_length=500)),
                ("effective_date", models.DateField()),
                ("fresh_until", models.DateField(blank=True, null=True)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "parameter_set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="assurance.customerparameterset",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_parameters",
                        to="assurance.financialscenario",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="LossEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("event_key", models.SlugField(max_length=100)),
                ("currency", models.CharField(max_length=3)),
                ("effect", models.CharField(blank=True, max_length=71)),
                ("business_process", models.CharField(blank=True, max_length=200)),
                ("trigger", models.CharField(blank=True, max_length=200)),
                ("correlation_group", models.CharField(blank=True, max_length=100)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loss_events",
                        to="assurance.financialscenario",
                    ),
                ),
            ],
            options={
                "ordering": ["scenario", "id"],
            },
        ),
        migrations.CreateModel(
            name="LossComponent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("component_key", models.SlugField(max_length=100)),
                (
                    "family",
                    models.CharField(
                        choices=[
                            ("business_interruption", "business_interruption"),
                            ("contractual", "contractual"),
                            ("customer_loss", "customer_loss"),
                            ("customer_restitution", "customer_restitution"),
                            ("data_and_ip", "data_and_ip"),
                            ("direct_financial", "direct_financial"),
                            ("incident_response", "incident_response"),
                            ("insurance", "insurance"),
                            ("legal", "legal"),
                            ("market_value", "market_value"),
                            ("notification", "notification"),
                            ("physical_operational", "physical_operational"),
                            ("recovery", "recovery"),
                            ("regulatory_compliance", "regulatory_compliance"),
                            ("remediation_investment", "remediation_investment"),
                            ("third_party_downstream", "third_party_downstream"),
                        ],
                        max_length=32,
                    ),
                ),
                ("formula_id", models.CharField(max_length=64)),
                ("formula_version", models.PositiveIntegerField()),
                ("as_of", models.DateField()),
                ("cited_parameters", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("estimated", "estimated"), ("unknown", "unknown")],
                        editable=False,
                        max_length=16,
                    ),
                ),
                (
                    "currency",
                    models.CharField(blank=True, editable=False, max_length=3),
                ),
                ("low", models.TextField(blank=True, editable=False)),
                ("base", models.TextField(blank=True, editable=False)),
                ("high", models.TextField(blank=True, editable=False)),
                (
                    "unknown_reason",
                    models.CharField(blank=True, editable=False, max_length=32),
                ),
                ("missing_inputs", models.JSONField(default=list, editable=False)),
                (
                    "insurance_treatment",
                    models.CharField(default="gross", editable=False, max_length=16),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "loss_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="assurance.lossevent",
                    ),
                ),
            ],
            options={
                "ordering": ["loss_event", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="customerparameterset",
            index=models.Index(
                fields=["deployment", "set_key"], name="assurance_econ_pset_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="customerparameterset",
            constraint=models.UniqueConstraint(
                fields=("deployment", "set_key", "version"),
                name="uq_econ_parameter_set_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="customerparameterset",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="ck_econ_parameter_set_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="customerparameterset",
            constraint=models.CheckConstraint(
                condition=models.Q(("variable_count__gte", 1)),
                name="ck_econ_parameter_set_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="financialparameter",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("scenario__isnull", False), ("parameter_set__isnull", True)
                    ),
                    models.Q(
                        ("scenario__isnull", True), ("parameter_set__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="ck_econ_parameter_one_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="financialparameter",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scenario__isnull", False)),
                fields=("scenario", "name"),
                name="uq_econ_parameter_scenario_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="financialparameter",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parameter_set__isnull", False)),
                fields=("parameter_set", "name"),
                name="uq_econ_parameter_set_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="financialparameter",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "unit__in",
                        [
                            "money",
                            "money_per_unit",
                            "money_per_hour",
                            "money_per_year",
                            "count",
                            "count_per_day",
                            "ratio",
                            "hours",
                            "days",
                            "years",
                        ],
                    )
                ),
                name="ck_econ_parameter_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="financialparameter",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "source_type__in",
                        [
                            "CUSTOMER_PROVIDED",
                            "MYTHOS_OBSERVED",
                            "CALCULATED",
                            "OFFICIAL_PUBLIC",
                            "LICENSED_MARKET",
                            "INDUSTRY_BENCHMARK",
                            "EXPERT_ESTIMATE",
                            "UNKNOWN",
                        ],
                    )
                ),
                name="ck_econ_parameter_source_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="lossevent",
            constraint=models.UniqueConstraint(
                fields=("scenario", "event_key"), name="uq_econ_loss_event_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="losscomponent",
            constraint=models.UniqueConstraint(
                fields=("loss_event", "component_key"),
                name="uq_econ_loss_component_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="losscomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "family__in",
                        [
                            "business_interruption",
                            "contractual",
                            "customer_loss",
                            "customer_restitution",
                            "data_and_ip",
                            "direct_financial",
                            "incident_response",
                            "insurance",
                            "legal",
                            "market_value",
                            "notification",
                            "physical_operational",
                            "recovery",
                            "regulatory_compliance",
                            "remediation_investment",
                            "third_party_downstream",
                        ],
                    )
                ),
                name="ck_econ_component_family",
            ),
        ),
        migrations.AddConstraint(
            model_name="losscomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["estimated", "unknown"])),
                name="ck_econ_component_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="losscomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(("insurance_treatment", "gross")),
                name="ck_econ_component_gross",
            ),
        ),
    ]
