# Generated by Django 5.2.5 on 2026-10-08 18:30
#
# SPINE Economic Exposure, the scenario builder (docs/economics/spec-v1.md,
# section 23): the causal graph a built scenario version rests on -- its effects
# (CausalEffect: a SPINE observed effect or a hypothetical one, bound to an asset
# and a business process, assigned to one template and to ONE loss event) and the
# findings that enable them (EffectFinding) -- and the build record (ScenarioBuild:
# the content digest of its inputs, unique per deployment, so the same inputs never
# build twice). New, empty tables: nothing is backfilled. All three are
# append-only and go with their deployment (CASCADE through the scenario). None has
# an account column, so removing an operator -- a stop -- never writes them; no
# constraint names a column a cascade or a SET_NULL writes. No foreign key has a
# reverse accessor (related_name "+"), so no related manager can move a recorded
# row to another parent past the append-only checks. The invariant is held in the
# database too: an effect key and a SPINE observation are each unique within a
# scenario, and an effect names one loss event.

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assurance", "0062_scenario_parameters_and_loss_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="CausalEffect",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("effect_key", models.SlugField(max_length=60)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("observed", "observed"),
                            ("hypothetical", "hypothetical"),
                        ],
                        max_length=16,
                    ),
                ),
                ("observed_effect", models.CharField(blank=True, max_length=36)),
                ("observation", models.CharField(blank=True, max_length=71)),
                ("spine_effect", models.CharField(blank=True, max_length=71)),
                ("effect_type", models.CharField(max_length=64)),
                ("asset", models.CharField(max_length=36)),
                ("business_process", models.CharField(max_length=64)),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("template_id", models.CharField(max_length=100)),
                ("template_version", models.PositiveIntegerField()),
                ("in_scope_of", models.JSONField(default=list)),
                ("lead", models.BooleanField(default=False)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "loss_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="assurance.lossevent",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="assurance.financialscenario",
                    ),
                ),
            ],
            options={
                "ordering": ["scenario", "id"],
            },
        ),
        migrations.CreateModel(
            name="EffectFinding",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("finding", models.CharField(max_length=36)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("prerequisite", "prerequisite"),
                            ("amplifier", "amplifier"),
                            ("alternate_path", "alternate_path"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "effect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="assurance.causaleffect",
                    ),
                ),
            ],
            options={
                "ordering": ["effect", "id"],
            },
        ),
        migrations.CreateModel(
            name="ScenarioBuild",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("build_digest", models.CharField(max_length=71)),
                ("builder_version", models.CharField(max_length=100)),
                ("grouping_version", models.CharField(max_length=100)),
                ("pack", models.CharField(max_length=100)),
                ("currency", models.CharField(max_length=3)),
                ("as_of", models.DateField()),
                ("inputs", models.JSONField()),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="assurance.deployment",
                    ),
                ),
                (
                    "parameter_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="assurance.customerparameterset",
                    ),
                ),
                (
                    "scenario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="assurance.financialscenario",
                    ),
                ),
            ],
            options={
                "ordering": ["deployment", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="causaleffect",
            constraint=models.UniqueConstraint(
                fields=("scenario", "effect_key"), name="uq_econ_effect_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="causaleffect",
            constraint=models.UniqueConstraint(
                condition=models.Q(("observation", ""), _negated=True),
                fields=("scenario", "observation"),
                name="uq_econ_effect_observation",
            ),
        ),
        migrations.AddConstraint(
            model_name="causaleffect",
            constraint=models.CheckConstraint(
                condition=models.Q(("origin__in", ("observed", "hypothetical"))),
                name="ck_econ_effect_origin",
            ),
        ),
        migrations.AddConstraint(
            model_name="causaleffect",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("origin", "observed"),
                        models.Q(("observation", ""), _negated=True),
                        models.Q(("observed_effect", ""), _negated=True),
                    ),
                    models.Q(
                        ("origin", "hypothetical"),
                        ("observation", ""),
                        ("observed_effect", ""),
                    ),
                    _connector="OR",
                ),
                name="ck_econ_effect_observed_has_observation",
            ),
        ),
        migrations.AddConstraint(
            model_name="effectfinding",
            constraint=models.UniqueConstraint(
                fields=("effect", "finding"), name="uq_econ_effect_finding"
            ),
        ),
        migrations.AddConstraint(
            model_name="effectfinding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("role__in", ("prerequisite", "amplifier", "alternate_path"))
                ),
                name="ck_econ_effect_finding_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="scenariobuild",
            constraint=models.UniqueConstraint(
                fields=("deployment", "build_digest"), name="uq_econ_build_digest"
            ),
        ),
    ]
