# Generated by Django 5.2.5 on 2026-09-29 07:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("route", models.CharField(max_length=128)),
                ("key", models.CharField(max_length=255)),
                ("request_digest", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("in_flight", "In flight -- no answer recorded yet"),
                            ("done", "Answered -- a replay is given this answer"),
                            (
                                "unknown",
                                "Unknown -- ended without an answer this backend observed",
                            ),
                        ],
                        default="in_flight",
                        max_length=16,
                    ),
                ),
                (
                    "response_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("response_body", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["expires_at"], name="idempotency_expires_a1e474_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="idempotency_user_id_ffa2e5_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "route", "key"),
                        name="uq_idempotency_key_per_account_route",
                    )
                ],
            },
        ),
    ]
